=== GNOME/dasher/Data/colours/colour.dtd
<!-- Colour schemes contain lists of colours to be used by Dasher -->

<!ELEMENT colours (palette*)>

<!ELEMENT palette (colour*)>
<!ATTLIST palette name CDATA #REQUIRED>

<!-- A list of rgb values -->
<!ELEMENT colour EMPTY>
<!ATTLIST colour r CDATA #REQUIRED>
<!ATTLIST colour g CDATA #REQUIRED>
<!ATTLIST colour b CDATA #REQUIRED>

=== GNOME/dasher/Data/colours/colour.ean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colours SYSTEM "colour.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<colours>
<palette name="Yellow on Black">
<!-- Summary:
    Colour scheme by Ean Price, black background and bright yellow symbols.
-->
<!-- background -->
<colour r="24" g="23" b="18"/>
<!-- mouse line -->
<colour r="63" g="61" b="56"/>
<!-- mouse position -->
<colour r="255" g="255" b="255"/>
<!-- box outlines -->
<colour r="99" g="99" b="99"/>
<!-- text -->
<colour r="255" g="255" b="0"/>
<!-- crosshairs -->
<colour r="0" g="0" b="0"/>
<!-- keyboard positioning -->
<colour r="0" g="0" b="0"/>
<!-- root node -->
<colour r="24" g="23" b="18"/>
<!-- control node -->
<colour r="80" g="80" b="80"/>
<!-- space -->
<colour r="0" g="0" b="0"/>
<!-- letters (10-109)-->
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<!-- groups (110-139) 110: red  111: yellow ;   112: GREEn;    113: RED  -->
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<!-- currently unused (130-137) -->
<colour r="0" g="0" b="0"/>
<colour r="0" g="0" b="0"/>
<colour r="0" g="0" b="0"/>
<colour r="0" g="0" b="0"/>
<colour r="255" g="160" b="100"/>
<colour r="255" g="100" b="204"/>
<colour r="200" g="255" b="20"/>
<colour r="150" g="255" b="50"/>
<!-- alternate control node -->
<colour r="80" g="80" b="80"/>
<!-- alternate space -->
<colour r="0" g="0" b="0"/>
<!-- alternate colours (140-239) -->
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<colour r="24" g="23" b="18"/>
<!-- Control mode colours -->
<!-- Green (240) -->
<colour r="0" g="255" b="0"/>
<!-- Amber (241) -->
<colour r="240" g="240" b="0"/>
<!-- Red (242) -->
<colour r="24" g="23" b="18"/>
</palette>
</colours>
