=== GNOME/dasher/Data/alphabets/alphabet.dtd
<!-- alphabets contains groups of valid symbols for use in Dasher,
along with some useful information. It does nothing to tell Dasher,
how those symbols may be used. -->

<!ELEMENT alphabets (alphabet*)>
<!--langcode Makes it possible to generate speech in language other
than system default. Enables bilingual use of dasher. 
For alphabets without spoken language i. e. musical symbols, make it empty string. -->
<!ATTLIST alphabets langcode CDATA #REQUIRED>

<!ELEMENT alphabet (orientation, encoding, palette, train, paragraph,
	space, control, conversionmode?, group*)>
<!ATTLIST alphabet name CDATA #REQUIRED>

<!-- Left-Right, Right-Left, Top-Bottom or Bottom-Top?
Which way up should Dasher do its rendering by default? -->
<!ELEMENT orientation EMPTY>
<!ATTLIST orientation type (LR|RL|TB|BT) #REQUIRED>

<!-- The encoding field just helps Dasher decide on some Localisation
issues. In theory it could see which characters are there and pick
a suitable file encoding and font. Sometimes this is difficult.
It does not dictate the file format. For example, traditionally Unix
and Windows use different encodings for some languages. A platform
should do what it thinks best given the vague group Dasher
has put the alphabet into. If this doesn't work out, the user
can over-ride the alphabet anyway. -->
<!ELEMENT encoding EMPTY>
<!ATTLIST encoding type (
	Arabic |
	Baltic |
	CentralEurope |
	ChineseSimplified |
	ChineseTraditional |
	Cyrillic |
	Greek |
	Hebrew |
	Japanese |
	Korean |
	Thai |
	Turkish |
	VietNam |
	Western ) #REQUIRED>

<!-- Colour palette -->
<!ELEMENT palette (#PCDATA)>

<!-- Default training file for this alphabet -->
<!ELEMENT train (#PCDATA)>

<!-- Language Code to track language -->
<!ELEMENT langcode (#PCDATA)>

<!-- Traditionally the paragraph character is rendered differently to all
others. Can set d (display) to "" to disable. -->
<!ELEMENT paragraph EMPTY>
<!ATTLIST paragraph d CDATA #REQUIRED>
<!ATTLIST paragraph f CDATA #IMPLIED>
<!ATTLIST paragraph b CDATA #IMPLIED>

<!-- Traditionally the space character is rendered differently to all
others. Can set both d (display) and t (text) to "" to disable. -->
<!ELEMENT space EMPTY>
<!ATTLIST space d CDATA #REQUIRED>
<!ATTLIST space t CDATA #REQUIRED>
<!ATTLIST space f CDATA #IMPLIED>
<!ATTLIST space b CDATA #IMPLIED>
<!ATTLIST space note CDATA #IMPLIED>

<!-- The control character is special, and not part of the main alphabet. -->
<!ELEMENT control EMPTY>
<!ATTLIST control d CDATA #REQUIRED>
<!ATTLIST control t CDATA #REQUIRED>
<!ATTLIST control f CDATA #IMPLIED>
<!ATTLIST control b CDATA #IMPLIED>

<!-- Conversion mode sets the way selected characters are converted into
a new one. In essence, set this to 1 for Japanese and 2 for Chinese. 0 is
the default, i.e., no conversion. -->
<!ELEMENT conversionmode EMPTY>
<!ATTLIST conversionmode id CDATA #REQUIRED>

<!-- Logical groups of symbols, eg name="Lower case letters" -->
<!ELEMENT group (s*)>
<!ATTLIST group name    CDATA #REQUIRED>
<!ATTLIST group label   CDATA #IMPLIED>
<!ATTLIST group visible CDATA #IMPLIED>
<!ATTLIST group b       CDATA #IMPLIED>

<!-- Symbols Dasher can use. It shows text d in the nodes and sends
text t to the edit box -->
<!ELEMENT s EMPTY>
<!ATTLIST s d CDATA #REQUIRED>
<!ATTLIST s t CDATA #REQUIRED>
<!ATTLIST s f CDATA #IMPLIED>
<!ATTLIST s b CDATA #IMPLIED>
<!ATTLIST s note CDATA #IMPLIED>

=== GNOME/dasher/Data/alphabets/alphabet.Igbo.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="ig">
<alphabet name="Igbo with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<control d="Control" t=""/>
<palette>Default</palette>
<train>training_Igbo_NG.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<group name="lower case letters" b="0">
<s d="&#x0061;" t="&#x0061;" />
<s d="&#x0062;" t="&#x0062;" />
<s d="&#x0063;" t="&#x0063;" />
<s d="&#x0064;" t="&#x0064;" />
<s d="&#x0065;" t="&#x0065;" />
<s d="&#x0066;" t="&#x0066;" />
<s d="&#x0067;" t="&#x0067;" />
<s d="&#x0068;" t="&#x0068;" />
<s d="&#x0069;" t="&#x0069;" />
<s d="&#x1ECB;" t="&#x1ECB;" />
<s d="&#x00EF;" t="&#x00EF;" />
<s d="&#x006A;" t="&#x006A;" />
<s d="&#x006B;" t="&#x006B;" />
<s d="&#x006C;" t="&#x006C;" />
<s d="&#x006D;" t="&#x006D;" />
<s d="&#x006E;" t="&#x006E;" />
<s d="&#x1E45;" t="&#x1E45;" />
<s d="&#x00F1;" t="&#x00F1;" />
<s d="&#x006F;" t="&#x006F;" />
<s d="&#x1ECD;" t="&#x1ECD;" />
<s d="&#x00F6;" t="&#x00F6;" />
<s d="&#x0070;" t="&#x0070;" />
<s d="&#x0071;" t="&#x0071;" />
<s d="&#x0072;" t="&#x0072;" />
<s d="&#x0073;" t="&#x0073;" />
<s d="&#x0074;" t="&#x0074;" />
<s d="&#x0075;" t="&#x0075;" />
<s d="&#x1EE5;" t="&#x1EE5;" />
<s d="&#x00FC;" t="&#x00FC;" />
<s d="&#x0076;" t="&#x0076;" />
<s d="&#x0077;" t="&#x0077;" />
<s d="&#x0078;" t="&#x0078;" />
<s d="&#x0079;" t="&#x0079;" />
<s d="&#x007A;" t="&#x007A;" />
</group> 
<group name="upper case letters" b="111"> 
<s d="&#x0041;" t="&#x0041;" />
<s d="&#x0042;" t="&#x0042;" />
<s d="&#x0043;" t="&#x0043;" />
<s d="&#x0044;" t="&#x0044;" />
<s d="&#x0045;" t="&#x0045;" />
<s d="&#x0046;" t="&#x0046;" />
<s d="&#x0047;" t="&#x0047;" />
<s d="&#x0048;" t="&#x0048;" />
<s d="&#x0049;" t="&#x0049;" />
<s d="&#x1ECA;" t="&#x1ECA;" />
<s d="&#x00CF;" t="&#x00CF;" />
<s d="&#x004A;" t="&#x004A;" />
<s d="&#x004B;" t="&#x004B;" />
<s d="&#x004C;" t="&#x004C;" />
<s d="&#x004D;" t="&#x004D;" />
<s d="&#x004E;" t="&#x004E;" />
<s d="&#x1E44;" t="&#x1E44;" />
<s d="&#x00D1;" t="&#x00D1;" />
<s d="&#x004F;" t="&#x004F;" />
<s d="&#x1ECC;" t="&#x1ECC;" />
<s d="&#x00D6;" t="&#x00D6;" />
<s d="&#x0050;" t="&#x0050;" />
<s d="&#x0051;" t="&#x0051;" />
<s d="&#x0052;" t="&#x0052;" />
<s d="&#x0053;" t="&#x0053;" />
<s d="&#x0054;" t="&#x0054;" />
<s d="&#x0055;" t="&#x0055;" />
<s d="&#x1EE4;" t="&#x1EE4;" />
<s d="&#x00DC;" t="&#x00DC;" />
<s d="&#x0056;" t="&#x0056;" />
<s d="&#x0057;" t="&#x0057;" />
<s d="&#x0058;" t="&#x0058;" />
<s d="&#x0059;" t="&#x0059;" />
<s d="&#x005A;" t="&#x005A;" />
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.latvian.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="lv">
<alphabet name="Latvie&#353;u / Latvian with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_latvian_LV.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="lower case letters" b="0">
<s d="&#x0061;" t="&#x0061;"  note=" A "   />
<s d="&#x0101;" t="&#x0101;"  note=" A WITH MACRON "   />
<s d="&#x0062;" t="&#x0062;"  note=" B "   />
<s d="&#x0063;" t="&#x0063;"  note=" C "   />
<s d="&#x010D;" t="&#x010D;"  note=" C WITH CARON "   />
<s d="&#x0064;" t="&#x0064;"  note=" D "   />
<s d="&#x0065;" t="&#x0065;"  note=" E "   />
<s d="&#x0113;" t="&#x0113;"  note=" E WITH MACRON "   />
<s d="&#x0066;" t="&#x0066;"  note=" F "   />
<s d="&#x0067;" t="&#x0067;"  note=" G "   />
<s d="&#x0123;" t="&#x0123;"  note=" G WITH CEDILLA "   />
<s d="&#x0068;" t="&#x0068;"  note=" H "   />
<s d="&#x0069;" t="&#x0069;"  note=" I "   />
<s d="&#x012B;" t="&#x012B;"  note=" I WITH MACRON "   />
<s d="&#x0079;" t="&#x0079;"  note=" Y "   />
<s d="&#x006A;" t="&#x006A;"  note=" J "   />
<s d="&#x006B;" t="&#x006B;"  note=" K "   />
<s d="&#x0137;" t="&#x0137;"  note=" K WITH CEDILLA "   />
<s d="&#x006C;" t="&#x006C;"  note=" L "   />
<s d="&#x013C;" t="&#x013C;"  note=" L WITH CEDILLA "   />
<s d="&#x006D;" t="&#x006D;"  note=" M "   />
<s d="&#x006E;" t="&#x006E;"  note=" N "   />
<s d="&#x0146;" t="&#x0146;"  note=" N WITH CEDILLA "   />
<s d="&#x006F;" t="&#x006F;"  note=" O "   />
<s d="&#x014D;" t="&#x014D;"  note=" O WITH MACRON "   />
<s d="&#x0070;" t="&#x0070;"  note=" P "   />
<s d="&#x0071;" t="&#x0071;"  note=" Q "   />
<s d="&#x0072;" t="&#x0072;"  note=" R "   />
<s d="&#x0157;" t="&#x0157;"  note=" R WITH CEDILLA "   />
<s d="&#x0073;" t="&#x0073;"  note=" S "   />
<s d="&#x0161;" t="&#x0161;"  note=" S WITH CARON "   />
<s d="&#x0074;" t="&#x0074;"  note=" T "   />
<s d="&#x0075;" t="&#x0075;"  note=" U "   />
<s d="&#x016B;" t="&#x016B;"  note=" U WITH MACRON "   />
<s d="&#x0076;" t="&#x0076;"  note=" V "   />
<s d="&#x0077;" t="&#x0077;"  note=" W "   />
<s d="&#x0078;" t="&#x0078;"  note=" X "   />
<s d="&#x007A;" t="&#x007A;"  note=" Z "   />
<s d="&#x017E;" t="&#x017E;"  note=" Z WITH CARON "   />
</group> 
<group name="upper case letters" b="111"> 
<s d="&#x0041;" t="&#x0041;"  note=" A "   />
<s d="&#x0100;" t="&#x0100;"  note=" A WITH MACRON "   />
<s d="&#x0042;" t="&#x0042;"  note=" B "   />
<s d="&#x0043;" t="&#x0043;"  note=" C "   />
<s d="&#x010C;" t="&#x010C;"  note=" C WITH CARON "   />
<s d="&#x0044;" t="&#x0044;"  note=" D "   />
<s d="&#x0045;" t="&#x0045;"  note=" E "   />
<s d="&#x0112;" t="&#x0112;"  note=" E WITH MACRON "   />
<s d="&#x0046;" t="&#x0046;"  note=" F "   />
<s d="&#x0047;" t="&#x0047;"  note=" G "   />
<s d="&#x0122;" t="&#x0122;"  note=" G WITH CEDILLA "   />
<s d="&#x0048;" t="&#x0048;"  note=" H "   />
<s d="&#x0049;" t="&#x0049;"  note=" I "   />
<s d="&#x012A;" t="&#x012A;"  note=" I WITH MACRON "   />
<s d="&#x0059;" t="&#x0059;"  note=" Y "   />
<s d="&#x004A;" t="&#x004A;"  note=" J "   />
<s d="&#x004B;" t="&#x004B;"  note=" K "   />
<s d="&#x0136;" t="&#x0136;"  note=" K WITH CEDILLA "   />
<s d="&#x004C;" t="&#x004C;"  note=" L "   />
<s d="&#x013B;" t="&#x013B;"  note=" L WITH CEDILLA "   />
<s d="&#x004D;" t="&#x004D;"  note=" M "   />
<s d="&#x004E;" t="&#x004E;"  note=" N "   />
<s d="&#x0145;" t="&#x0145;"  note=" N WITH CEDILLA "   />
<s d="&#x004F;" t="&#x004F;"  note=" O "   />
<s d="&#x014C;" t="&#x014C;"  note=" O WITH MACRON "   />
<s d="&#x0050;" t="&#x0050;"  note=" P "   />
<s d="&#x0051;" t="&#x0051;"  note=" Q "   />
<s d="&#x0052;" t="&#x0052;"  note=" R "   />
<s d="&#x0156;" t="&#x0156;"  note=" R WITH CEDILLA "   />
<s d="&#x0053;" t="&#x0053;"  note=" S "   />
<s d="&#x0160;" t="&#x0160;"  note=" S WITH CARON "   />
<s d="&#x0054;" t="&#x0054;"  note=" T "   />
<s d="&#x0055;" t="&#x0055;"  note=" U "   />
<s d="&#x016A;" t="&#x016A;"  note=" U WITH MACRON "   />
<s d="&#x0056;" t="&#x0056;"  note=" V "   />
<s d="&#x0057;" t="&#x0057;"  note=" W "   />
<s d="&#x0058;" t="&#x0058;"  note=" X "   />
<s d="&#x005A;" t="&#x005A;"  note=" Z "   />
<s d="&#x017D;" t="&#x017D;"  note=" Z WITH CARON "   />
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.akan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="ak">
<alphabet name="Akan (Twi) with lots of punctuation">
<!-- same as Adangbe and Ga and Akan and Ewe -->
<!--- http://www.ethnologue.com/show_language.asp?code=TWS -->
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_akan_GH.txt</train>
<space d="&#x25a1;" t=" " b="9"/>
<control d="Control" t="" b="8"/>
<paragraph d="&#182;" b="9"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="&#x025B;" t="&#x025B;" note="OPEN LETTER E" b="13"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="&#x014B;" t="&#x014B;" note="SMALL LETTER ENG" b="20"/>
<s d="o" t="o" b="24"/>
<s d="&#x0254;" t="&#x0254;" note="OPEN LETTER O" b="21"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="&#x0190;" t="&#x0190;" note="CAPITAL OPEN LETTER E" b="13"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="&#x014A;" t="&#x014A;" note="CAPITAL LETTER ENG" b="20"/>
<s d="O" t="O" b="24"/>
<s d="&#x0186;" t="&#x0186;" note="CAPITAL OPEN LETTER O" b="21"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="105"/>
<s d="3" t="3" b="91"/>
<s d="4" t="4" b="106"/>
<s d="5" t="5" b="92"/>
<s d="6" t="6" b="107"/>
<s d="7" t="7" b="93"/>
<s d="8" t="8" b="108"/>
<s d="9" t="9" b="94"/>
<s d="0" t="0" b="109"/>
</group>
<group name="Punctuation" b="112">
<s b="90" d="%" t="%"/>
<s b="91" d="*" t="*"/>
<s b="92" d="+" t="+"/>
<s b="93" d="=" t="="/>
<s b="94" d="/" t="/"/>
<s b="95" d="#" t="#"/>
<s b="96" d="$" t="$"/>
<s b="97" d="|" t="|"/>
<s b="98" d="\" t="\"/>
<s b="99" d="~" t="~"/>
<s b="95" d="^" t="^"/>
<s b="96" d="_" t="_"/>
<s b="97" d="&amp;" t="&amp;"/> 
<s b="98" d="@" t="@"/>
<s b="105" d="[" t="["/>
<s b="106" d="]" t="]"/>
<s b="107" d="{" t="{"/>
<s b="108" d="}" t="}"/>
<s b="109" d="&lt;" t="&lt;"/>
<s b="105" d="&gt;" t="&gt;"/>
<s b="106" d="(" t="("/>
<s b="107" d=")" t=")"/>
<s b="108" d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s b="109" d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s b="106" d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s b="107" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s b="108" d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="109" d="`" t="`" note="left quote from keyboard" />
<s b="105" d="&apos;" t="&apos;" note="apostrophe" />
<s b="100" d="-" t="-"/>
<s b="101" d=":" t=":"/>
<s b="102" d=";" t=";"/>
<s b="103" d="?" t="?"/>
<s b="104" d="!" t="!"/>
<s b="100" d="," t=","/>
<s b="104" d="." t="."/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.Thai2.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="th">
<alphabet name="Thai / &#3616;&#3634;&#3625;&#3634;&#3652;&#3607;&#3618; with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_Thai_TH.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="Thai letters" b="0">
<s d="&#x0E01;" t="&#x0E01;" note="0E01 KO KAI"/>
<s d="&#x0E02;" t="&#x0E02;" note="0E02 KHO KHAI"/>
<s d="&#x0E03;" t="&#x0E03;" note="0E03 KHO KHUAT"/>
<s d="&#x0E04;" t="&#x0E04;" note="0E04 KHO KHWAI"/>
<s d="&#x0E05;" t="&#x0E05;" note="0E05 KHO KHON"/>
<s d="&#x0E06;" t="&#x0E06;" note="0E06 KHO RAKHANG"/>
<s d="&#x0E07;" t="&#x0E07;" note="0E07 NGO NGU"/>
<s d="&#x0E08;" t="&#x0E08;" note="0E08 CHO CHAN"/>
<s d="&#x0E09;" t="&#x0E09;" note="0E09 CHO CHING"/>
<s d="&#x0E0A;" t="&#x0E0A;" note="0E0A CHO CHANG"/>
<s d="&#x0E0B;" t="&#x0E0B;" note="0E0B SO SO"/>
<s d="&#x0E0C;" t="&#x0E0C;" note="0E0C CHO CHOE"/>
<s d="&#x0E0D;" t="&#x0E0D;" note="0E0D YO YING"/>
<s d="&#x0E0E;" t="&#x0E0E;" note="0E0E DO CHADA"/>
<s d="&#x0E0F;" t="&#x0E0F;" note="0E0F TO PATAK"/>
<s d="&#x0E10;" t="&#x0E10;" note="0E10 THO THAN"/>
<s d="&#x0E11;" t="&#x0E11;" note="0E11 THO NANGMONTHO"/>
<s d="&#x0E12;" t="&#x0E12;" note="0E12 THO PHUTHAO"/>
<s d="&#x0E13;" t="&#x0E13;" note="0E13 NO NEN"/>
<s d="&#x0E14;" t="&#x0E14;" note="0E14 DO DEK"/>
<s d="&#x0E15;" t="&#x0E15;" note="0E15 TO TAO"/>
<s d="&#x0E16;" t="&#x0E16;" note="0E16 THO THUNG"/>
<s d="&#x0E17;" t="&#x0E17;" note="0E17 THO THAHAN"/>
<s d="&#x0E18;" t="&#x0E18;" note="0E18 THO THONG"/>
<s d="&#x0E19;" t="&#x0E19;" note="0E19 NO NU"/>
<s d="&#x0E1A;" t="&#x0E1A;" note="0E1A BO BAIMAI"/>
<s d="&#x0E1B;" t="&#x0E1B;" note="0E1B PO PLA"/>
<s d="&#x0E1C;" t="&#x0E1C;" note="0E1C PHO PHUNG"/>
<s d="&#x0E1D;" t="&#x0E1D;" note="0E1D FO FA"/>
<s d="&#x0E1E;" t="&#x0E1E;" note="0E1E PHO PHAN"/>
<s d="&#x0E1F;" t="&#x0E1F;" note="0E1F FO FAN"/>
<s d="&#x0E20;" t="&#x0E20;" note="0E20 PHO SAMPHAO"/>
<s d="&#x0E21;" t="&#x0E21;" note="0E21 MO MA"/>
<s d="&#x0E22;" t="&#x0E22;" note="0E22 YO YAK"/>
<s d="&#x0E23;" t="&#x0E23;" note="0E23 RO RUA"/>
<s d="&#x0E25;" t="&#x0E25;" note="0E25 LO LING"/>
<s d="&#x0E27;" t="&#x0E27;" note="0E27 WO WAEN"/>
<s d="&#x0E28;" t="&#x0E28;" note="0E28 SO SALA"/>
<s d="&#x0E29;" t="&#x0E29;" note="0E29 SO RUSI"/>
<s d="&#x0E2A;" t="&#x0E2A;" note="0E2A SO SUA"/>
<s d="&#x0E2B;" t="&#x0E2B;" note="0E2B HO HIP"/>
<s d="&#x0E2C;" t="&#x0E2C;" note="0E2C LO CHULA"/>
<s d="&#x0E2D;" t="&#x0E2D;" note="0E2D O ANG"/>
<s d="&#x0E2E;" t="&#x0E2E;" note="0E2E HO NOKHUK"/>
<s d="&#x0E24;" t="&#x0E24;" note="0E24 RU"/>
<s d="&#x0E26;" t="&#x0E26;" note="0E26 LU"/>
<s d="&#x25cc;&#x0E46;" t="&#x0E46;" note="THAI CHARACTER MAIYAMOK - CHECK - OK" />
<s d="&#x0E2F;" t="&#x0E2F;" note="0E2F PAIYANNOI - CHECK - OK"/>
</group>
<group name="Character modifiers?"  b="111">
<s d="&#x25cc;&#x0E48;" t="&#x0E48;" note="0E48	 MAI EK - CHECK - OK"/>
<s d="&#x25cc;&#x0E49;" t="&#x0E49;" note="0E49	 MAI THO - CHECK - OK"/>
<s d="&#x25cc;&#x0E4A;" t="&#x0E4A;" note="0E4A	 MAI TRI - CHECK - OK"/>
<s d="&#x25cc;&#x0E4B;" t="&#x0E4B;" note="0E4B	 MAI CHATTAWA - CHECK - OK"/>
<s d="&#x25cc;&#x0E31;" t="&#x0E31;" note="MAI HAN-AKAT" />
<s d="&#x25cc;&#x0E47;" t="&#x0E47;" note="0E47	 MAITAIKHU - CHECK - OK"/>
<s d="&#x25cc;&#x0E4C;" t="&#x0E4C;" note="0E4C	 THANTHAKHAT - CHECK  -OK"/>
<s d="&#x25cc;&#x0E30;" t="&#x0E30;" note="SARA A" />
<s d="&#x25cc;&#x0E32;" t="&#x0E32;" />
<s d="&#x25cc;&#x0E45;" t="&#x0E45;" />
<s d="&#x25cc;&#x0E33;" t="&#x0E33;" />
<s d="&#x25cc;&#x0E34;" t="&#x0E34;" />
<s d="&#x25cc;&#x0E35;" t="&#x0E35;" />
<s d="&#x25cc;&#x0E36;" t="&#x0E36;" />
<s d="&#x25cc;&#x0E37;" t="&#x0E37;" />
<s d="&#x25cc;&#x0E38;" t="&#x0E38;" />
<s d="&#x25cc;&#x0E39;" t="&#x0E39;" />
<s d="&#x0E40;&#x25cc;" t="&#x0E40;" note="0E40	 SARA E"/>	    
<s d="&#x0E41;&#x25cc;" t="&#x0E41;" note="0E41	 SARA AE"/>	    
<s d="&#x0E42;&#x25cc;" t="&#x0E42;" note="0E42	 SARA O"/>	    
<s d="&#x0E43;&#x25cc;" t="&#x0E43;" note="0E43	 SARA AI MAIMUAN"/> 
<s d="&#x0E44;&#x25cc;" t="&#x0E44;" note="0E44	 SARA AI MAIMALAI"/>
<s d="&#x25cc;&#x0E3A;" t="&#x0E3A;" note="0E3A PHINTHU - CHECK - Bali-Sansakrit"/>
<s d="&#x25cc;&#x0E4D;" t="&#x0E4D;" note="0E4D	 NIKHAHIT - CHECK - Bali-Sansakrit"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="91"/>
<s d="3" t="3" b="92"/>
<s d="4" t="4" b="93"/>
<s d="5" t="5" b="94"/>
<s d="6" t="6" b="90"/>
<s d="7" t="7" b="91"/>
<s d="8" t="8" b="92"/>
<s d="9" t="9" b="93"/>
<s d="0" t="0" b="94"/>
</group>
<group name="Punctuation" b="112">
<s b="90" d="%" t="%"/>
<s b="91" d="*" t="*"/>
<s b="92" d="+" t="+"/>
<s b="93" d="=" t="="/>
<s b="94" d="/" t="/"/>
<s b="95" d="#" t="#"/>
<s d="&#x0E3F;" t="&#x0E3F;" note="0E3F	THAI CURRENCY SYMBOL BAHT"/>
<s b="98" d="$" t="$"/>
<s b="99" d="|" t="|"/>
<s b="95" d="\" t="\"/>
<s b="96" d="~" t="~"/>
<s b="97" d="^" t="^"/>
<s b="98" d="_" t="_"/>
<s b="99" d="&amp;" t="&amp;"/> 
<s b="95" d="@" t="@"/>
<s b="105" d="[" t="["/>
<s b="106" d="]" t="]"/>
<s b="107" d="{" t="{"/>
<s b="108" d="}" t="}"/>
<s b="109" d="&lt;" t="&lt;"/>
<s b="105" d="&gt;" t="&gt;"/>
<s b="106" d="(" t="("/>
<s b="107" d=")" t=")"/>
<s b="108" d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s b="109" d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s b="106" d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s b="107" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s b="108" d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="109" d="`" t="`" note="left quote from keyboard" />
<s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<s b="9"  d="&#x25CA;" t="&#x9;" note="TAB (represented by a diamond)"/>
<s b="100" d="-" t="-"/>
<s b="101" d=":" t=":"/>
<s b="102" d=";" t=";"/>
<s b="103" d="?" t="?"/>
<s b="104" d="!" t="!"/>
<s b="100" d="," t=","/>
<s d="&#183;" t="." b="104"/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Src/Tools/UserLogLoadTest/alphabet.english.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets>
<alphabet name="English alphabet - limited punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_english_GB.txt</train>
<paragraph d="&#182;" b="9"/>
<space d="_" t=" " b="9"/>
<control d="Control" t="" b="8"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A" b="12"/>
<s d="B" t="B" b="13"/>
<s d="C" t="C" b="14"/>
<s d="D" t="D" b="15"/>
<s d="E" t="E" b="16"/>
<s d="F" t="F" b="17"/>
<s d="G" t="G" b="18"/>
<s d="H" t="H" b="19"/>
<s d="I" t="I" b="20"/>
<s d="J" t="J" b="21"/>
<s d="K" t="K" b="22"/>
<s d="L" t="L" b="23"/>
<s d="M" t="M" b="24"/>
<s d="N" t="N" b="25"/>
<s d="O" t="O" b="26"/>
<s d="P" t="P" b="27"/>
<s d="Q" t="Q" b="28"/>
<s d="R" t="R" b="29"/>
<s d="S" t="S" b="30"/>
<s d="T" t="T" b="31"/>
<s d="U" t="U" b="32"/>
<s d="V" t="V" b="33"/>
<s d="W" t="W" b="34"/>
<s d="X" t="X" b="35"/>
<s d="Y" t="Y" b="36"/>
<s d="Z" t="Z" b="37"/>
</group>
<group name="Punctuation" b="112">
<s d="&amp;" t="&amp;" b="11"/>
<s d="&quot;" t="&quot;" b="12"/>
<s d="&apos;" t="&apos;" b="13"/>
<s d="?" t="?" b="14"/>
<s d="!" t="!" b="15"/>
<s d="," t="," b="16"/>
<s d="." t="." b="17"/>
</group>
</alphabet>
<alphabet name="English alphabet with lots of punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_english_GB.txt</train>
<space d="_" t=" "/>
<control d="Control" t=""/>
<paragraph d="&#182;" b="9"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a"/>
<s d="b" t="b"/>
<s d="c" t="c"/>
<s d="d" t="d"/>
<s d="e" t="e"/>
<s d="f" t="f"/>
<s d="g" t="g"/>
<s d="h" t="h"/>
<s d="i" t="i"/>
<s d="j" t="j"/>
<s d="k" t="k"/>
<s d="l" t="l"/>
<s d="m" t="m"/>
<s d="n" t="n"/>
<s d="o" t="o"/>
<s d="p" t="p"/>
<s d="q" t="q"/>
<s d="r" t="r"/>
<s d="s" t="s"/>
<s d="t" t="t"/>
<s d="u" t="u"/>
<s d="v" t="v"/>
<s d="w" t="w"/>
<s d="x" t="x"/>
<s d="y" t="y"/>
<s d="z" t="z"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A"/>
<s d="B" t="B"/>
<s d="C" t="C"/>
<s d="D" t="D"/>
<s d="E" t="E"/>
<s d="F" t="F"/>
<s d="G" t="G"/>
<s d="H" t="H"/>
<s d="I" t="I"/>
<s d="J" t="J"/>
<s d="K" t="K"/>
<s d="L" t="L"/>
<s d="M" t="M"/>
<s d="N" t="N"/>
<s d="O" t="O"/>
<s d="P" t="P"/>
<s d="Q" t="Q"/>
<s d="R" t="R"/>
<s d="S" t="S"/>
<s d="T" t="T"/>
<s d="U" t="U"/>
<s d="V" t="V"/>
<s d="W" t="W"/>
<s d="X" t="X"/>
<s d="Y" t="Y"/>
<s d="Z" t="Z"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
</alphabets>
