=== GNOME/dasher/Data/alphabets/alphabet.dtd
<!-- alphabets contains groups of valid symbols for use in Dasher,
along with some useful information. It does nothing to tell Dasher,
how those symbols may be used. -->

<!ELEMENT alphabets (alphabet*)>
<!--langcode Makes it possible to generate speech in language other
than system default. Enables bilingual use of dasher. 
For alphabets without spoken language i. e. musical symbols, make it empty string. -->
<!ATTLIST alphabets langcode CDATA #REQUIRED>

<!ELEMENT alphabet (orientation, encoding, palette, train, paragraph,
	space, control, conversionmode?, group*)>
<!ATTLIST alphabet name CDATA #REQUIRED>

<!-- Left-Right, Right-Left, Top-Bottom or Bottom-Top?
Which way up should Dasher do its rendering by default? -->
<!ELEMENT orientation EMPTY>
<!ATTLIST orientation type (LR|RL|TB|BT) #REQUIRED>

<!-- The encoding field just helps Dasher decide on some Localisation
issues. In theory it could see which characters are there and pick
a suitable file encoding and font. Sometimes this is difficult.
It does not dictate the file format. For example, traditionally Unix
and Windows use different encodings for some languages. A platform
should do what it thinks best given the vague group Dasher
has put the alphabet into. If this doesn't work out, the user
can over-ride the alphabet anyway. -->
<!ELEMENT encoding EMPTY>
<!ATTLIST encoding type (
	Arabic |
	Baltic |
	CentralEurope |
	ChineseSimplified |
	ChineseTraditional |
	Cyrillic |
	Greek |
	Hebrew |
	Japanese |
	Korean |
	Thai |
	Turkish |
	VietNam |
	Western ) #REQUIRED>

<!-- Colour palette -->
<!ELEMENT palette (#PCDATA)>

<!-- Default training file for this alphabet -->
<!ELEMENT train (#PCDATA)>

<!-- Language Code to track language -->
<!ELEMENT langcode (#PCDATA)>

<!-- Traditionally the paragraph character is rendered differently to all
others. Can set d (display) to "" to disable. -->
<!ELEMENT paragraph EMPTY>
<!ATTLIST paragraph d CDATA #REQUIRED>
<!ATTLIST paragraph f CDATA #IMPLIED>
<!ATTLIST paragraph b CDATA #IMPLIED>

<!-- Traditionally the space character is rendered differently to all
others. Can set both d (display) and t (text) to "" to disable. -->
<!ELEMENT space EMPTY>
<!ATTLIST space d CDATA #REQUIRED>
<!ATTLIST space t CDATA #REQUIRED>
<!ATTLIST space f CDATA #IMPLIED>
<!ATTLIST space b CDATA #IMPLIED>
<!ATTLIST space note CDATA #IMPLIED>

<!-- The control character is special, and not part of the main alphabet. -->
<!ELEMENT control EMPTY>
<!ATTLIST control d CDATA #REQUIRED>
<!ATTLIST control t CDATA #REQUIRED>
<!ATTLIST control f CDATA #IMPLIED>
<!ATTLIST control b CDATA #IMPLIED>

<!-- Conversion mode sets the way selected characters are converted into
a new one. In essence, set this to 1 for Japanese and 2 for Chinese. 0 is
the default, i.e., no conversion. -->
<!ELEMENT conversionmode EMPTY>
<!ATTLIST conversionmode id CDATA #REQUIRED>

<!-- Logical groups of symbols, eg name="Lower case letters" -->
<!ELEMENT group (s*)>
<!ATTLIST group name    CDATA #REQUIRED>
<!ATTLIST group label   CDATA #IMPLIED>
<!ATTLIST group visible CDATA #IMPLIED>
<!ATTLIST group b       CDATA #IMPLIED>

<!-- Symbols Dasher can use. It shows text d in the nodes and sends
text t to the edit box -->
<!ELEMENT s EMPTY>
<!ATTLIST s d CDATA #REQUIRED>
<!ATTLIST s t CDATA #REQUIRED>
<!ATTLIST s f CDATA #IMPLIED>
<!ATTLIST s b CDATA #IMPLIED>
<!ATTLIST s note CDATA #IMPLIED>

=== GNOME/dasher/Data/alphabets/alphabet.Urdu.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet-nest.xsl"?>
<alphabets langcode="ur">
<alphabet name="Urdu with punctuation and numerals">
<orientation type="RL"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_Urdu_PK.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="letters" b="0">
<group name="Vowels etc" b="110">
<s d="&#x25cc;&#x064B;" t="&#x064B;"   b="90"  note="FATHATAN - RARE"  />
<s d="&#x25cc;&#x064C;" t="&#x064C;"   b="91"  note="dammatan - RARE"  />
<s d="&#x25cc;&#x064D;" t="&#x064D;"   b="92"  note="kasratan - RARE"  />
<s d="&#x25cc;&#x064E;" t="&#x064E;"   b="93"  note="fatha "  />
<s d="&#x25cc;&#x064F;" t="&#x064F;"   b="94"  note="damma"  />
<s d="&#x25cc;&#x0650;" t="&#x0650;"   b="90"  note="kasra "  />
<s d="&#x25cc;&#x0651;" t="&#x0651;"   b="91"  note="shadda"  />
<s d="&#x25cc;&#x0652;" t="&#x0652;"   b="92"  note="sukun - RARE"  />
<!-- <s d="&#x0653;" t="&#x0653;"      note="maddah above (sometimes used to make combined characters)"  /> -->
<s d="&#x0654;" t="&#x0654;"    b="93"  note="hamza above (sometimes used to make combined characters)"  />
<!-- <s d="&#x0655;" t="&#x0655;"  b="70"  note="hamza below (sometimes used to make combined characters)"  /> -->
<s d="&#x25cc;&#x0670;" t="&#x0670;"   b="94"  note="superscript alef"  />
</group>
<group name="Hamza" b="60">
<s d="&#x0622;" t="&#x0622;"  b="80" note="ARABIC LETTER ALEF WITH MADDA ABOVE  "  />
<s d="&#x0627;" t="&#x0627;" b="70"   note=" ALEF  "  />
<s d="&#x0621;" t="&#x0621;" b="70" note=" HAMZA  RARE"  />
<!-- <s d="&#x0623;" t="&#x0623;"  b="70" note="ARABIC LETTER ALEF WITH HAMZA ABOVE   RARE "  /> -->
<!-- <s d="&#x0672;" t="&#x0672;"  b="80" note="ARABIC LETTER ALEF WITH WAVY HAMZA ABOVE  "  /> -->
<!-- <s d="&#x0624;" t="&#x0624;"  b="79"  note="ARABIC LETTER WAW WITH HAMZA ABOVE    RARE "  /> -->
<!-- <s d="&#x0625;" t="&#x0625;"  b="70" note="ARABIC LETTER ALEF WITH HAMZA BELOW   RARE "  /> -->
</group>
<group b="61" >
<s d="&#x0628;" t="&#x0628;"  b="81"  note=" BEH  "  />
<!-- <s d="&#x0629;" t="&#x0629;"   b="71"  note=" TEH MARBUTA   RARE "  /> -->
<s d="&#x062A;" t="&#x062A;"  b="71"  note=" TEH  "  />
<s d="&#x0679;" t="&#x0679;"  b="81" note=" TTEH "  />
<s d="&#x062B;" t="&#x062B;"  b="71" note=" THEH  "  />
</group>
<group b="62" >
<s d="&#x062C;" t="&#x062C;"  b="72" note=" JEEM  "  />
<s d="&#x0686;" t="&#x0686;"  b="72" note="TCHEH "  />
<s d="&#x062D;" t="&#x062D;"  b="82" note=" HAH  "  />
<s d="&#x062E;" t="&#x062E;"   b="72"  note=" KHAH  "  />
</group>
<group b="63" >
<s d="&#x062F;" t="&#x062F;"   b="73"  note=" DAL  "  />
<s d="&#x0688;" t="&#x0688;"   b="83"  note="DDAL"  />
<s d="&#x0630;" t="&#x0630;"   b="73"  note=" THAL  "  />
<s d="&#x0631;" t="&#x0631;"   b="83"  note=" REH  "  />
<s d="&#x0691;" t="&#x0691;"   b="73" note=" RREH "  />
<s d="&#x0632;" t="&#x0632;"   b="83"  note=" ZAIN  "  />
<s d="&#x0698;" t="&#x0698;"   b="73" note="JEH "  />
</group>
<group b="64" >
<s d="&#x0633;" t="&#x0633;"   b="74"  note=" SEEN  "  />
<s d="&#x0634;" t="&#x0634;"   b="84"  note=" SHEEN  "  />
</group>
<group b="65" >
<s d="&#x0635;" t="&#x0635;"   b="75"  note=" SAD  "  />
<s d="&#x0636;" t="&#x0636;"   b="85"  note=" DAD  "  />
<s d="&#x0637;" t="&#x0637;"   b="75"  note=" TAH  "  />
<s d="&#x0638;" t="&#x0638;"   b="85"  note=" ZAH  "  />
</group>
<group b="66" >
<s d="&#x0639;" t="&#x0639;"   b="76"  note=" AIN  "  />
<s d="&#x063A;" t="&#x063A;"   b="86"  note=" GHAIN  "  />
<s d="&#x0641;" t="&#x0641;"   b="76"  note=" FEH  "  />
<s d="&#x0642;" t="&#x0642;"   b="86"  note=" QAF  "  />
</group>
<group b="67" >
<!-- <s d="&#x0643;" t="&#x0643;"   b="76"  note=" KAF  "  /> -->
<s d="&#x0644;" t="&#x0644;"   b="77"  note=" LAM  "  />
<s d="&#x0645;" t="&#x0645;"   b="87"  note=" MEEM  "  />
<s d="&#x0646;" t="&#x0646;"   b="77"  note=" NOON  "  />
<!-- <s d="&#x0647;" t="&#x0647;"   b="78"  note=" HEH  "  /> -->
</group>
<group b="68" >
<s d="&#x0648;" t="&#x0648;"   b="78"  note=" WAW  "  />
<!-- <s d="&#x0649;" t="&#x0649;"   b="89"  note=" ALEF MAKSURA (Looks like YEH!)"  /> -->
<!-- <s d="&#x064A;" t="&#x064A;"   b="79"  note=" YEH  "  /> -->
<s d="&#x0626;" t="&#x0626;"  b="88" note=" YEH WITH HAMZA ABOVE  "  />
</group>
<!-- note unused group colour 69/79/89 -->
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="105"/>
<s d="3" t="3" b="91"/>
<s d="4" t="4" b="106"/>
<s d="5" t="5" b="92"/>
<s d="6" t="6" b="107"/>
<s d="7" t="7" b="93"/>
<s d="8" t="8" b="108"/>
<s d="9" t="9" b="94"/>
<s d="0" t="0" b="109"/>
</group>
<group name="Arabic-Indic numbers" b="116">
<s d="&#x0661;" t="&#x0661;"  b="90"	 note="ONE"/>
<s d="&#x0662;" t="&#x0662;"  b="105" note="TWO"/>
<s d="&#x0663;" t="&#x0663;"  b="91"	 note="THREE"/>
<s d="&#x0664;" t="&#x0664;"  b="106" note="FOUR"/>
<s d="&#x0665;" t="&#x0665;"  b="92"	 note="FIVE"/>
<s d="&#x0666;" t="&#x0666;"  b="107" note="SIX"/>
<s d="&#x0667;" t="&#x0667;"  b="93"	 note="SEVEN"/>
<s d="&#x0668;" t="&#x0668;"  b="108" note="EIGHT"/>
<s d="&#x0669;" t="&#x0669;"  b="94"	 note="NINE"/>
<s d="&#x0660;" t="&#x0660;"  b="109" note="ZERO"/>
</group>
<group name="ASCII Punctuation" b="114">
<s b="99" d="~" t="~"/>
<s b="98" d="@" t="@"/>
<s b="95" d="#" t="#"/>
<s b="96" d="$" t="$"/>
<s b="90" d="%" t="%"/>
<s b="95" d="^" t="^"/>
<s b="97" d="&amp;" t="&amp;"/> 
<s b="91" d="*" t="*"/>
<s b="100" d="-" t="-"/>
<s b="96" d="_" t="_"/>
<s b="98" d="\" t="\"/>
<s b="97" d="|" t="|"/>
</group>
<group name="Punctuation" b="112">
<s b="90"    d="&#xfdfc;" t="&#xfdfc;"  note="currency"/>
<s b="91" d="&#x066A;" t="&#x066A;" note="Arabic percent"/>
<s b="92" d="+" t="+"/>
<s b="93" d="&#x2212;" t="&#x2212;" note="minus"/>
<s b="94" d="&#x00d7;" t="&#x00d7;" note="times"/>
<s b="90" d="&#x00f7;" t="&#x00f7;" note="divide"/>
<s b="91" d="=" t="="/>
<s b="92" d="/" t="/" note="keep in persian as separator"/>
<s b="109" d="&#x200F;&lt;&#x200F;" t="&lt;"/>
<s b="105" d="&#x200F;&gt;&#x200F;" t="&gt;"/>
<s b="107" d="&#x200F;{&#x200F;" t="{"/>
<s b="108" d="&#x200F;}&#x200F;" t="}"/>
<s b="105" d="&#x200F;[&#x200F;" t="["/>
<s b="106" d="&#x200F;]&#x200F;" t="]"/>
<s b="106" d="&#x200F;(&#x200F;" t="("/>
<s b="107" d="&#x200F;)&#x200F;" t=")"/>
<s d="&#x200F;&#x2039;&#x200F;" t="&#x2039;" note="French opening single quotation mark" />
<s d="&#x200F;&#x203A;&#x200F;" t="&#x203A;" note="French opening single quotation mark" />
<s d="&#x200F;&#x00AB;&#x200F;" t="&#x00AB;" note="French left double quotation mark" />
<s d="&#x200F;&#x00BB;&#x200F;" t="&#x00BB;" note="French right double quotation mark" />
<s b="100" d="&#x2010;" t="&#x2010;"/>
<s b="100" d="!" t="!"/>
<s b="101" d="&#x061F;" t="&#x061F;"  note="Arabic question mark"/>
<s b="101" d=":" t=":"/>
<s b="102" d="&#x061B;" t="&#x061B;"  note="Arabic semicolon"/>
<s b="103"  d="&#x060C;" t="&#x060C;"  note="Arabic comma"/>
<s b="104" d="." t="."/>
</group>
<group name="Joiners" b="111">
<s b="73" t="&#x200c;" d="&#x2225;" note="Zero width non-joiner"/>
<s b="74" t="&#x200d;" d="&#x2195;" note="Zero width joiner"/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.ogham.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="pgl">
<alphabet name="Ogham">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_ogham_XX.txt</train>
<paragraph d="&#182;" b="9"/>
<space d="&#x25a1;" t=" " b="9"/>
<control d="Control" t="" b="8"/>
<group name="Ogham" >
<s d="&#x1681;" t="&#x1681;" note=" OGHAM LETTER BEITH  "/>
<s d="&#x1682;" t="&#x1682;" note=" OGHAM LETTER LUIS  "/>
<s d="&#x1683;" t="&#x1683;" note=" OGHAM LETTER FEARN  "/>
<s d="&#x1684;" t="&#x1684;" note=" OGHAM LETTER SAIL  "/>
<s d="&#x1685;" t="&#x1685;" note=" OGHAM LETTER NION  "/>
<s d="&#x1686;" t="&#x1686;" note=" OGHAM LETTER UATH  "/>
<s d="&#x1687;" t="&#x1687;" note=" OGHAM LETTER DAIR  "/>
<s d="&#x1688;" t="&#x1688;" note=" OGHAM LETTER TINNE  "/>
<s d="&#x1689;" t="&#x1689;" note=" OGHAM LETTER COLL  "/>
<s d="&#x168A;" t="&#x168A;" note=" OGHAM LETTER CEIRT  "/>
<s d="&#x168B;" t="&#x168B;" note=" OGHAM LETTER MUIN  "/>
<s d="&#x168C;" t="&#x168C;" note=" OGHAM LETTER GORT  "/>
<s d="&#x168D;" t="&#x168D;" note=" OGHAM LETTER NGEADAL  "/>
<s d="&#x168E;" t="&#x168E;" note=" OGHAM LETTER STRAIF  "/>
<s d="&#x168F;" t="&#x168F;" note=" OGHAM LETTER RUIS  "/>
<s d="&#x1690;" t="&#x1690;" note=" OGHAM LETTER AILM  "/>
<s d="&#x1691;" t="&#x1691;" note=" OGHAM LETTER ONN  "/>
<s d="&#x1692;" t="&#x1692;" note=" OGHAM LETTER UR  "/>
<s d="&#x1693;" t="&#x1693;" note=" OGHAM LETTER EADHADH  "/>
<s d="&#x1694;" t="&#x1694;" note=" OGHAM LETTER IODHADH  "/>
<s d="&#x1695;" t="&#x1695;" note=" OGHAM LETTER EABHADH  "/>
<s d="&#x1696;" t="&#x1696;" note=" OGHAM LETTER OR  "/>
<s d="&#x1697;" t="&#x1697;" note=" OGHAM LETTER UILLEANN  "/>
<s d="&#x1698;" t="&#x1698;" note=" OGHAM LETTER IFIN  "/>
<s d="&#x1699;" t="&#x1699;" note=" OGHAM LETTER EAMHANCHOLL  "/>
<s d="&#x169A;" t="&#x169A;" note=" OGHAM LETTER PEITH  "/>
</group>
<group name="Ogham marks" b="0">
<s d="&#x169B;" t="&#x169B;" note=" OGHAM FEATHER MARK  "/>
<s d="&#x169C;" t="&#x169C;" note=" OGHAM REVERSED FEATHER MARK "/>
<s d="&#x1680;" t="&#x1680;" note=" OGHAM SPACE MARK  " b="9"/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.Hebrew.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="he">
<alphabet name="Ivrit / Hebrew (&#1506;&#1489;&#1512;&#1497;&#1514;)">
<!-- created by David MacKay with advice from Liz Pushett -->
<orientation type="RL"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_hebrew_IL.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="Hebrew letters" b="0">
<s d="&#x05d0;" t="&#x05d0;" note="Alef"/>
<s d="&#x05d1;" t="&#x05d1;" />
<s d="&#x05d2;" t="&#x05d2;" />
<s d="&#x05d3;" t="&#x05d3;" />
<s d="&#x05d4;" t="&#x05d4;" />
<s d="&#x05d5;" t="&#x05d5;" />
<s d="&#x05d6;" t="&#x05d6;" />
<s d="&#x05d7;" t="&#x05d7;" />
<s d="&#x05d8;" t="&#x05d8;" />
<s d="&#x05d9;" t="&#x05d9;" />
<s d="&#x05dB;" t="&#x05dB;" />
<s d="&#x05dA;" t="&#x05dA;" />
<s d="&#x05dC;" t="&#x05dC;" />
<s d="&#x05de;" t="&#x05de;" note="Mem" />
<s d="&#x05dd;" t="&#x05dd;" note="Final Mem"/>
<s d="&#x05e0;" t="&#x05e0;" note="Nun" />
<s d="&#x05dF;" t="&#x05dF;" note="Final Nun" />
<s d="&#x05e1;" t="&#x05e1;" />
<s d="&#x05e2;" t="&#x05e2;" />
<s d="&#x05e4;" t="&#x05e4;" />
<s d="&#x05e3;" t="&#x05e3;" />
<s d="&#x05e6;" t="&#x05e6;" />
<s d="&#x05e5;" t="&#x05e5;" />
<s d="&#x05e7;" t="&#x05e7;" />
<s d="&#x05e8;" t="&#x05e8;" />
<s d="&#x05e9;" t="&#x05e9;" />
<s d="&#x05eA;" t="&#x05eA;" />
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="&#x20AA;" t="&#x20AA;"  note="shekel"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s b="109" d="&#x200F;&lt;&#x200F;" t="&lt;"/>
<s b="105" d="&#x200F;&gt;&#x200F;" t="&gt;"/>
<s b="107" d="&#x200F;{&#x200F;" t="{"/>
<s b="108" d="&#x200F;}&#x200F;" t="}"/>
<s b="105" d="&#x200F;[&#x200F;" t="["/>
<s b="106" d="&#x200F;]&#x200F;" t="]"/>
<s b="106" d="&#x200F;(&#x200F;" t="("/>
<s b="107" d="&#x200F;)&#x200F;" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
<alphabet name="Ivrit / Hebrew (&#1506;&#1489;&#1512;&#1497;&#1514;) with digraphs, vowels, and marks">
<!-- created by David MacKay with advice from Liz Pushett and http://www.i18nguy.com/unicode/hebrew.html -->
<orientation type="RL"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_hebrew_IL.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="Hebrew letters" b="0">
<s d="&#x05d0;" t="&#x05d0;" />
<s d="&#x05d1;" t="&#x05d1;" />
<s d="&#x05d2;" t="&#x05d2;" />
<s d="&#x05d3;" t="&#x05d3;" />
<s d="&#x05d4;" t="&#x05d4;" />
<s d="&#x05d5;" t="&#x05d5;" />
<s d="&#x05d6;" t="&#x05d6;" />
<s d="&#x05d7;" t="&#x05d7;" />
<s d="&#x05d8;" t="&#x05d8;" />
<s d="&#x05d9;" t="&#x05d9;" />
<s d="&#x05dB;" t="&#x05dB;" />
<s d="&#x05dA;" t="&#x05dA;" />
<s d="&#x05dC;" t="&#x05dC;" />
<s d="&#x05de;" t="&#x05de;" />
<s d="&#x05dd;" t="&#x05dd;" />
<s d="&#x05e0;" t="&#x05e0;" />
<s d="&#x05dF;" t="&#x05dF;" />
<s d="&#x05e1;" t="&#x05e1;" />
<s d="&#x05e2;" t="&#x05e2;" />
<s d="&#x05e4;" t="&#x05e4;" />
<s d="&#x05e3;" t="&#x05e3;" />
<s d="&#x05e6;" t="&#x05e6;" />
<s d="&#x05e5;" t="&#x05e5;" />
<s d="&#x05e7;" t="&#x05e7;" />
<s d="&#x05e8;" t="&#x05e8;" />
<s d="&#x05e9;" t="&#x05e9;" />
<s d="&#x05eA;" t="&#x05eA;" />
</group>
<group name="Yiddish digraph characters" b="115">
<s d="&#x05F0;" t="&#x05F0;" note="double vav"/>
<s d="&#x05F1;" t="&#x05F1;" note="vav yod"/>
<s d="&#x05F2;" t="&#x05F2;" note="double yod"/>
</group>
<group name="Hebrew punctuation characters" b="112">
<s d="&#x05BE;" t="&#x05BE;" note="maqaf"/>
<s d="&#x05C0;" t="&#x05C0;" note="paseq"/>
<s d="&#x05C3;" t="&#x05C3;"  note="sof pasuq" />
<s d="&#x05F3;" t="&#x05F3;"  note="Geresh"/>
<s d="&#x05F4;" t="&#x05F4;"  note="Garshayim"/>
</group>	          
<group name="Points (Vowels) (Nequdot, &#x5E0;&#x5E7;&#x5D5;&#x5D3;&#x5D5;&#x5EA;)" b="112">
<s d="&#x25cc;&#x05B0;" t="&#x05B0;" note="vowel: combining sheva" />
<s d="&#x25cc;&#x05B1;" t="&#x05B1;" note="vowel: combining hatef segol" />
<s d="&#x25cc;&#x05B2;" t="&#x05B2;" note="vowel: combining" />
<s d="&#x25cc;&#x05B3;" t="&#x05B3;" note="vowel: combining" />
<s d="&#x25cc;&#x05B4;" t="&#x05B4;" note="vowel: combining"/>
<s d="&#x25cc;&#x05B5;" t="&#x05B5;" note="vowel: combining"/>
<s d="&#x25cc;&#x05B6;" t="&#x05B6;" note="vowel: combining"/>
<s d="&#x25cc;&#x05B7;" t="&#x05B7;" note="vowel: combining"/>
<s d="&#x25cc;&#x05B8;" t="&#x05B8;" note="vowel: combining"/>
<s d="&#x25cc;&#x05B9;" t="&#x05B9;" note="vowel: combining"/>
<s d="&#x25cc;&#x05BB;" t="&#x05BB;" note="vowel: combining"/>
<s d="&#x25cc;&#x05BC;" t="&#x05BC;" note="vowel: combining"/>
<s d="&#x25cc;&#x05BD;" t="&#x05BD;" note="vowel: combining"/>
<s d="&#x25cc;&#x05BF;" t="&#x05BF;" note="vowel: combining rafe"/>
<s d="&#x25cc;&#x05C1;" t="&#x05C1;" note="vowel: combining shin dot"/>
<s d="&#x25cc;&#x05C2;" t="&#x05C2;" note="vowel: combining sin dot"/>
<s d="&#x25cc;&#x05C4;" t="&#x05C4;" note="vowel: combining mark upper dot"/>
</group>	          
<group name="Hebrew cantillation marks (Teamim, &#x5D8;&#x5E2;&#x5DE;&#x5D9;&#x5DD;)" b="111">
<s d="&#x25cc;&#x0591;" t="&#x0591;" />
<s d="&#x25cc;&#x0592;" t="&#x0592;" />
<s d="&#x25cc;&#x0593;" t="&#x0593;" />
<s d="&#x25cc;&#x0594;" t="&#x0594;" />
<s d="&#x25cc;&#x0595;" t="&#x0595;" />
<s d="&#x25cc;&#x0596;" t="&#x0596;" />
<s d="&#x25cc;&#x0597;" t="&#x0597;" />
<s d="&#x25cc;&#x0598;" t="&#x0598;" />
<s d="&#x25cc;&#x0599;" t="&#x0599;" />
<s d="&#x25cc;&#x059A;" t="&#x059A;" />
<s d="&#x25cc;&#x059B;" t="&#x059B;" />
<s d="&#x25cc;&#x059C;" t="&#x059C;" />
<s d="&#x25cc;&#x059D;" t="&#x059D;" />
<s d="&#x25cc;&#x059E;" t="&#x059E;" />
<s d="&#x25cc;&#x059F;" t="&#x059F;" />
<s d="&#x25cc;&#x05A0;" t="&#x05A0;" />
<s d="&#x25cc;&#x05A1;" t="&#x05A1;" />
<s d="&#x25cc;&#x05A3;" t="&#x05A3;" />
<s d="&#x25cc;&#x05A4;" t="&#x05A4;" />
<s d="&#x25cc;&#x05A5;" t="&#x05A5;" />
<s d="&#x25cc;&#x05A6;" t="&#x05A6;" />
<s d="&#x25cc;&#x05A7;" t="&#x05A7;" />
<s d="&#x25cc;&#x05A8;" t="&#x05A8;" />
<s d="&#x25cc;&#x05A9;" t="&#x05A9;" />
<s d="&#x25cc;&#x05AA;" t="&#x05AA;" />
<s d="&#x25cc;&#x05AB;" t="&#x05AB;" />
<s d="&#x25cc;&#x05AC;" t="&#x05AC;" />
<s d="&#x25cc;&#x05AD;" t="&#x05AD;" />
<s d="&#x25cc;&#x05AE;" t="&#x05AE;" />
<s d="&#x25cc;&#x05AF;" t="&#x05AF;" />
</group>	          
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="&#x20AA;" t="&#x20AA;"  note="shekel"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s b="109" d="&#x200F;&lt;&#x200F;" t="&lt;"/>
<s b="105" d="&#x200F;&gt;&#x200F;" t="&gt;"/>
<s b="107" d="&#x200F;{&#x200F;" t="{"/>
<s b="108" d="&#x200F;}&#x200F;" t="}"/>
<s b="105" d="&#x200F;[&#x200F;" t="["/>
<s b="106" d="&#x200F;]&#x200F;" t="]"/>
<s b="106" d="&#x200F;(&#x200F;" t="("/>
<s b="107" d="&#x200F;)&#x200F;" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.Ndebele.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="nd">
<alphabet name="Ndebele alphabet with numerals and lots of punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_Ndebele_ZA.txt</train>
<space d="&#x25a1;" t=" " b="9"/>
<control d="Control" t="" b="8"/>
<paragraph d="&#182;" b="9"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a"/>
<s d="b" t="b"/>
<s d="c" t="c"/>
<s d="d" t="d"/>
<s d="e" t="e"/>
<s d="f" t="f"/>
<s d="g" t="g"/>
<s d="h" t="h"/>
<s d="i" t="i"/>
<s d="j" t="j"/>
<s d="k" t="k"/>
<s d="l" t="l"/>
<s d="m" t="m"/>
<s d="n" t="n"/>
<s d="o" t="o"/>
<s d="p" t="p"/>
<s d="q" t="q"/>
<s d="r" t="r"/>
<s d="s" t="s"/>
<s d="t" t="t"/>
<s d="u" t="u"/>
<s d="v" t="v"/>
<s d="w" t="w"/>
<s d="x" t="x"/>
<s d="y" t="y"/>
<s d="z" t="z"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A"/>
<s d="B" t="B"/>
<s d="C" t="C"/>
<s d="D" t="D"/>
<s d="E" t="E"/>
<s d="F" t="F"/>
<s d="G" t="G"/>
<s d="H" t="H"/>
<s d="I" t="I"/>
<s d="J" t="J"/>
<s d="K" t="K"/>
<s d="L" t="L"/>
<s d="M" t="M"/>
<s d="N" t="N"/>
<s d="O" t="O"/>
<s d="P" t="P"/>
<s d="Q" t="Q"/>
<s d="R" t="R"/>
<s d="S" t="S"/>
<s d="T" t="T"/>
<s d="U" t="U"/>
<s d="V" t="V"/>
<s d="W" t="W"/>
<s d="X" t="X"/>
<s d="Y" t="Y"/>
<s d="Z" t="Z"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&quot;" t="&quot;"/>
<s d="`" t="`"/>
<s d="&apos;" t="&apos;"/>
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
</alphabets>
