=== GNOME/dasher/Data/alphabets/alphabet.dtd
<!-- alphabets contains groups of valid symbols for use in Dasher,
along with some useful information. It does nothing to tell Dasher,
how those symbols may be used. -->

<!ELEMENT alphabets (alphabet*)>
<!--langcode Makes it possible to generate speech in language other
than system default. Enables bilingual use of dasher. 
For alphabets without spoken language i. e. musical symbols, make it empty string. -->
<!ATTLIST alphabets langcode CDATA #REQUIRED>

<!ELEMENT alphabet (orientation, encoding, palette, train, paragraph,
	space, control, conversionmode?, group*)>
<!ATTLIST alphabet name CDATA #REQUIRED>

<!-- Left-Right, Right-Left, Top-Bottom or Bottom-Top?
Which way up should Dasher do its rendering by default? -->
<!ELEMENT orientation EMPTY>
<!ATTLIST orientation type (LR|RL|TB|BT) #REQUIRED>

<!-- The encoding field just helps Dasher decide on some Localisation
issues. In theory it could see which characters are there and pick
a suitable file encoding and font. Sometimes this is difficult.
It does not dictate the file format. For example, traditionally Unix
and Windows use different encodings for some languages. A platform
should do what it thinks best given the vague group Dasher
has put the alphabet into. If this doesn't work out, the user
can over-ride the alphabet anyway. -->
<!ELEMENT encoding EMPTY>
<!ATTLIST encoding type (
	Arabic |
	Baltic |
	CentralEurope |
	ChineseSimplified |
	ChineseTraditional |
	Cyrillic |
	Greek |
	Hebrew |
	Japanese |
	Korean |
	Thai |
	Turkish |
	VietNam |
	Western ) #REQUIRED>

<!-- Colour palette -->
<!ELEMENT palette (#PCDATA)>

<!-- Default training file for this alphabet -->
<!ELEMENT train (#PCDATA)>

<!-- Language Code to track language -->
<!ELEMENT langcode (#PCDATA)>

<!-- Traditionally the paragraph character is rendered differently to all
others. Can set d (display) to "" to disable. -->
<!ELEMENT paragraph EMPTY>
<!ATTLIST paragraph d CDATA #REQUIRED>
<!ATTLIST paragraph f CDATA #IMPLIED>
<!ATTLIST paragraph b CDATA #IMPLIED>

<!-- Traditionally the space character is rendered differently to all
others. Can set both d (display) and t (text) to "" to disable. -->
<!ELEMENT space EMPTY>
<!ATTLIST space d CDATA #REQUIRED>
<!ATTLIST space t CDATA #REQUIRED>
<!ATTLIST space f CDATA #IMPLIED>
<!ATTLIST space b CDATA #IMPLIED>
<!ATTLIST space note CDATA #IMPLIED>

<!-- The control character is special, and not part of the main alphabet. -->
<!ELEMENT control EMPTY>
<!ATTLIST control d CDATA #REQUIRED>
<!ATTLIST control t CDATA #REQUIRED>
<!ATTLIST control f CDATA #IMPLIED>
<!ATTLIST control b CDATA #IMPLIED>

<!-- Conversion mode sets the way selected characters are converted into
a new one. In essence, set this to 1 for Japanese and 2 for Chinese. 0 is
the default, i.e., no conversion. -->
<!ELEMENT conversionmode EMPTY>
<!ATTLIST conversionmode id CDATA #REQUIRED>

<!-- Logical groups of symbols, eg name="Lower case letters" -->
<!ELEMENT group (s*)>
<!ATTLIST group name    CDATA #REQUIRED>
<!ATTLIST group label   CDATA #IMPLIED>
<!ATTLIST group visible CDATA #IMPLIED>
<!ATTLIST group b       CDATA #IMPLIED>

<!-- Symbols Dasher can use. It shows text d in the nodes and sends
text t to the edit box -->
<!ELEMENT s EMPTY>
<!ATTLIST s d CDATA #REQUIRED>
<!ATTLIST s t CDATA #REQUIRED>
<!ATTLIST s f CDATA #IMPLIED>
<!ATTLIST s b CDATA #IMPLIED>
<!ATTLIST s note CDATA #IMPLIED>

=== GNOME/dasher/Data/alphabets/alphabet.cherokee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="chr">
<alphabet name="Cherokee">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_cherokee_US.txt</train>
<paragraph d="&#182;" b="9"/>
<space d="&#x25a1;" t=" " b="9"/>
<control d="Control" t="" b="8"/>
<group name="A" b="190" >
<s d="&#x13A0;" t="&#x13A0;" note=" CHEROKEE LETTER A  "/>
<s d="&#x13A1;" t="&#x13A1;" note=" CHEROKEE LETTER E  "/>
<s d="&#x13A2;" t="&#x13A2;" note=" CHEROKEE LETTER I  "/>
<s d="&#x13A3;" t="&#x13A3;" note=" CHEROKEE LETTER O  "/>
<s d="&#x13A4;" t="&#x13A4;" note=" CHEROKEE LETTER U  "/>
<s d="&#x13A5;" t="&#x13A5;" note=" CHEROKEE LETTER V  "/>
</group>
<group name="GA" b="191" >
<s d="&#x13A6;" t="&#x13A6;" note=" CHEROKEE LETTER GA  "/>
<s d="&#x13A7;" t="&#x13A7;" note=" CHEROKEE LETTER KA  "/>
<s d="&#x13A8;" t="&#x13A8;" note=" CHEROKEE LETTER GE  "/>
<s d="&#x13A9;" t="&#x13A9;" note=" CHEROKEE LETTER GI  "/>
<s d="&#x13AA;" t="&#x13AA;" note=" CHEROKEE LETTER GO  "/>
<s d="&#x13AB;" t="&#x13AB;" note=" CHEROKEE LETTER GU  "/>
<s d="&#x13AC;" t="&#x13AC;" note=" CHEROKEE LETTER GV  "/>
</group>
<group name="HA" b="192" >
<s d="&#x13AD;" t="&#x13AD;" note=" CHEROKEE LETTER HA  "/>
<s d="&#x13AE;" t="&#x13AE;" note=" CHEROKEE LETTER HE  "/>
<s d="&#x13AF;" t="&#x13AF;" note=" CHEROKEE LETTER HI  "/>
<s d="&#x13B0;" t="&#x13B0;" note=" CHEROKEE LETTER HO  "/>
<s d="&#x13B1;" t="&#x13B1;" note=" CHEROKEE LETTER HU  "/>
<s d="&#x13B2;" t="&#x13B2;" note=" CHEROKEE LETTER HV  "/>
</group>
<group name="LA" b="193" >
<s d="&#x13B3;" t="&#x13B3;" note=" CHEROKEE LETTER LA  "/>
<s d="&#x13B4;" t="&#x13B4;" note=" CHEROKEE LETTER LE  "/>
<s d="&#x13B5;" t="&#x13B5;" note=" CHEROKEE LETTER LI  "/>
<s d="&#x13B6;" t="&#x13B6;" note=" CHEROKEE LETTER LO  "/>
<s d="&#x13B7;" t="&#x13B7;" note=" CHEROKEE LETTER LU  "/>
<s d="&#x13B8;" t="&#x13B8;" note=" CHEROKEE LETTER LV  "/>
</group>
<group name="MA" b="194" >
<s d="&#x13B9;" t="&#x13B9;" note=" CHEROKEE LETTER MA  "/>
<s d="&#x13BA;" t="&#x13BA;" note=" CHEROKEE LETTER ME  "/>
<s d="&#x13BB;" t="&#x13BB;" note=" CHEROKEE LETTER MI  "/>
<s d="&#x13BC;" t="&#x13BC;" note=" CHEROKEE LETTER MO  "/>
<s d="&#x13BD;" t="&#x13BD;" note=" CHEROKEE LETTER MU  "/>
</group>
<group name="NA" b="195" >
<s d="&#x13BE;" t="&#x13BE;" note=" CHEROKEE LETTER NA  "/>
<s d="&#x13BF;" t="&#x13BF;" note=" CHEROKEE LETTER HNA  "/>
<s d="&#x13C0;" t="&#x13C0;" note=" CHEROKEE LETTER NAH  "/>
<s d="&#x13C1;" t="&#x13C1;" note=" CHEROKEE LETTER NE  "/>
<s d="&#x13C2;" t="&#x13C2;" note=" CHEROKEE LETTER NI  "/>
<s d="&#x13C3;" t="&#x13C3;" note=" CHEROKEE LETTER NO  "/>
<s d="&#x13C4;" t="&#x13C4;" note=" CHEROKEE LETTER NU  "/>
<s d="&#x13C5;" t="&#x13C5;" note=" CHEROKEE LETTER NV  "/>
</group>
<group name="QUA" b="196" >
<s d="&#x13C6;" t="&#x13C6;" note=" CHEROKEE LETTER QUA  "/>
<s d="&#x13C7;" t="&#x13C7;" note=" CHEROKEE LETTER QUE  "/>
<s d="&#x13C8;" t="&#x13C8;" note=" CHEROKEE LETTER QUI  "/>
<s d="&#x13C9;" t="&#x13C9;" note=" CHEROKEE LETTER QUO  "/>
<s d="&#x13CA;" t="&#x13CA;" note=" CHEROKEE LETTER QUU  "/>
<s d="&#x13CB;" t="&#x13CB;" note=" CHEROKEE LETTER QUV  "/>
</group>
<group name="SA" b="197" >
<s d="&#x13CC;" t="&#x13CC;" note=" CHEROKEE LETTER SA  "/>
<s d="&#x13CD;" t="&#x13CD;" note=" CHEROKEE LETTER S  "/>
<s d="&#x13CE;" t="&#x13CE;" note=" CHEROKEE LETTER SE  "/>
<s d="&#x13CF;" t="&#x13CF;" note=" CHEROKEE LETTER SI  "/>
<s d="&#x13D0;" t="&#x13D0;" note=" CHEROKEE LETTER SO  "/>
<s d="&#x13D1;" t="&#x13D1;" note=" CHEROKEE LETTER SU  "/>
<s d="&#x13D2;" t="&#x13D2;" note=" CHEROKEE LETTER SV  "/>
</group>
<group name="DA" b="198" >
<s d="&#x13D3;" t="&#x13D3;" note=" CHEROKEE LETTER DA  "/>
<s d="&#x13D4;" t="&#x13D4;" note=" CHEROKEE LETTER TA  "/>
<s d="&#x13D5;" t="&#x13D5;" note=" CHEROKEE LETTER DE  "/>
<s d="&#x13D6;" t="&#x13D6;" note=" CHEROKEE LETTER TE  "/>
<s d="&#x13D7;" t="&#x13D7;" note=" CHEROKEE LETTER DI  "/>
<s d="&#x13D8;" t="&#x13D8;" note=" CHEROKEE LETTER TI  "/>
<s d="&#x13D9;" t="&#x13D9;" note=" CHEROKEE LETTER DO  "/>
<s d="&#x13DA;" t="&#x13DA;" note=" CHEROKEE LETTER DU  "/>
<s d="&#x13DB;" t="&#x13DB;" note=" CHEROKEE LETTER DV  "/>
</group>
<group name="DL" b="199" >
<s d="&#x13DC;" t="&#x13DC;" note=" CHEROKEE LETTER DLA  "/>
<s d="&#x13DD;" t="&#x13DD;" note=" CHEROKEE LETTER TLA  "/>
<s d="&#x13DE;" t="&#x13DE;" note=" CHEROKEE LETTER TLE  "/>
<s d="&#x13DF;" t="&#x13DF;" note=" CHEROKEE LETTER TLI  "/>
<s d="&#x13E0;" t="&#x13E0;" note=" CHEROKEE LETTER TLO  "/>
<s d="&#x13E1;" t="&#x13E1;" note=" CHEROKEE LETTER TLU  "/>
<s d="&#x13E2;" t="&#x13E2;" note=" CHEROKEE LETTER TLV  "/>
</group>
<group name="TS" b="190" >
<s d="&#x13E3;" t="&#x13E3;" note=" CHEROKEE LETTER TSA  "/>
<s d="&#x13E4;" t="&#x13E4;" note=" CHEROKEE LETTER TSE  "/>
<s d="&#x13E5;" t="&#x13E5;" note=" CHEROKEE LETTER TSI  "/>
<s d="&#x13E6;" t="&#x13E6;" note=" CHEROKEE LETTER TSO  "/>
<s d="&#x13E7;" t="&#x13E7;" note=" CHEROKEE LETTER TSU  "/>
<s d="&#x13E8;" t="&#x13E8;" note=" CHEROKEE LETTER TSV  "/>
</group>
<group name="WA" b="191" >
<s d="&#x13E9;" t="&#x13E9;" note=" CHEROKEE LETTER WA  "/>
<s d="&#x13EA;" t="&#x13EA;" note=" CHEROKEE LETTER WE  "/>
<s d="&#x13EB;" t="&#x13EB;" note=" CHEROKEE LETTER WI  "/>
<s d="&#x13EC;" t="&#x13EC;" note=" CHEROKEE LETTER WO  "/>
<s d="&#x13ED;" t="&#x13ED;" note=" CHEROKEE LETTER WU  "/>
<s d="&#x13EE;" t="&#x13EE;" note=" CHEROKEE LETTER WV  "/>
</group>
<group name="YA" b="192" >
<s d="&#x13EF;" t="&#x13EF;" note=" CHEROKEE LETTER YA  "/>
<s d="&#x13F0;" t="&#x13F0;" note=" CHEROKEE LETTER YE  "/>
<s d="&#x13F1;" t="&#x13F1;" note=" CHEROKEE LETTER YI  "/>
<s d="&#x13F2;" t="&#x13F2;" note=" CHEROKEE LETTER YO  "/>
<s d="&#x13F3;" t="&#x13F3;" note=" CHEROKEE LETTER YU  "/>
<s d="&#x13F4;" t="&#x13F4;" note=" CHEROKEE LETTER YV "/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.catalan.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="ca">
<alphabet name="Catal&#x00E0; / Catalan with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_catalan_ES.txt</train>
<space d="&#x25a1;" t=" " b="9" note="box" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="lower case letters" b="0">
<s d="&#x0061;" t="&#x0061;"  note=" A "   />
<s d="&#x00E0;" t="&#x00E0;"  note=" A WITH GRAVE "   />
<s d="&#x0062;" t="&#x0062;"  note=" B "   />
<s d="&#x0063;" t="&#x0063;"  note=" C "   />
<s d="&#x00E7;" t="&#x00E7;"  note=" C WITH CEDILLA "   />
<s d="&#x0064;" t="&#x0064;"  note=" D "   />
<s d="&#x0065;" t="&#x0065;"  note=" E "   />
<s d="&#x00E9;" t="&#x00E9;"  note=" E WITH ACUTE "   />
<s d="&#x00E8;" t="&#x00E8;"  note=" E WITH GRAVE "   />
<s d="&#x0066;" t="&#x0066;"  note=" F "   />
<s d="&#x0067;" t="&#x0067;"  note=" G "   />
<s d="&#x0068;" t="&#x0068;"  note=" H "   />
<s d="&#x0069;" t="&#x0069;"  note=" I "   />
<s d="&#x00ED;" t="&#x00ED;"  note=" I WITH ACUTE "   />
<s d="&#x00EF;" t="&#x00EF;"  note=" I WITH DIAERESIS "   />
<s d="&#x006A;" t="&#x006A;"  note=" J "   />
<s d="&#x006B;" t="&#x006B;"  note=" K "   />
<s d="&#x006C;" t="&#x006C;"  note=" L "   />
<s d="&#x006D;" t="&#x006D;"  note=" M "   />
<s d="&#x006E;" t="&#x006E;"  note=" N "   />
<s d="&#x006F;" t="&#x006F;"  note=" O "   />
<s d="&#x00F3;" t="&#x00F3;"  note=" O WITH ACUTE "   />
<s d="&#x00F2;" t="&#x00F2;"  note=" O WITH GRAVE "   />
<s d="&#x0070;" t="&#x0070;"  note=" P "   />
<s d="&#x0071;" t="&#x0071;"  note=" Q "   />
<s d="&#x0072;" t="&#x0072;"  note=" R "   />
<s d="&#x0073;" t="&#x0073;"  note=" S "   />
<s d="&#x0074;" t="&#x0074;"  note=" T "   />
<s d="&#x0075;" t="&#x0075;"  note=" U "   />
<s d="&#x00FA;" t="&#x00FA;"  note=" U WITH ACUTE "   />
<s d="&#x00FC;" t="&#x00FC;"  note=" U WITH DIAERESIS "   />
<s d="&#x0076;" t="&#x0076;"  note=" V "   />
<s d="&#x0077;" t="&#x0077;"  note=" W "   />
<s d="&#x0078;" t="&#x0078;"  note=" X "   />
<s d="&#x0079;" t="&#x0079;"  note=" Y "   />
<s d="&#x007A;" t="&#x007A;"  note=" Z "   />
</group> 
<group name="upper case letters" b="111"> 
<s d="&#x0041;" t="&#x0041;"  note=" A "   />
<s d="&#x00C0;" t="&#x00C0;"  note=" A WITH GRAVE "   />
<s d="&#x0042;" t="&#x0042;"  note=" B "   />
<s d="&#x0043;" t="&#x0043;"  note=" C "   />
<s d="&#x00C7;" t="&#x00C7;"  note=" C WITH CEDILLA "   />
<s d="&#x0044;" t="&#x0044;"  note=" D "   />
<s d="&#x0045;" t="&#x0045;"  note=" E "   />
<s d="&#x00C9;" t="&#x00C9;"  note=" E WITH ACUTE "   />
<s d="&#x00C8;" t="&#x00C8;"  note=" E WITH GRAVE "   />
<s d="&#x0046;" t="&#x0046;"  note=" F "   />
<s d="&#x0047;" t="&#x0047;"  note=" G "   />
<s d="&#x0048;" t="&#x0048;"  note=" H "   />
<s d="&#x0049;" t="&#x0049;"  note=" I "   />
<s d="&#x00CD;" t="&#x00CD;"  note=" I WITH ACUTE "   />
<s d="&#x00CF;" t="&#x00CF;"  note=" I WITH DIAERESIS "   />
<s d="&#x004A;" t="&#x004A;"  note=" J "   />
<s d="&#x004B;" t="&#x004B;"  note=" K "   />
<s d="&#x004C;" t="&#x004C;"  note=" L "   />
<s d="&#x004D;" t="&#x004D;"  note=" M "   />
<s d="&#x004E;" t="&#x004E;"  note=" N "   />
<s d="&#x004F;" t="&#x004F;"  note=" O "   />
<s d="&#x00D3;" t="&#x00D3;"  note=" O WITH ACUTE "   />
<s d="&#x00D2;" t="&#x00D2;"  note=" O WITH GRAVE "   />
<s d="&#x0050;" t="&#x0050;"  note=" P "   />
<s d="&#x0051;" t="&#x0051;"  note=" Q "   />
<s d="&#x0052;" t="&#x0052;"  note=" R "   />
<s d="&#x0053;" t="&#x0053;"  note=" S "   />
<s d="&#x0054;" t="&#x0054;"  note=" T "   />
<s d="&#x0055;" t="&#x0055;"  note=" U "   />
<s d="&#x00DA;" t="&#x00DA;"  note=" U WITH ACUTE "   />
<s d="&#x00DC;" t="&#x00DC;"  note=" U WITH DIAERESIS "   />
<s d="&#x0056;" t="&#x0056;"  note=" V "   />
<s d="&#x0057;" t="&#x0057;"  note=" W "   />
<s d="&#x0058;" t="&#x0058;"  note=" X "   />
<s d="&#x0059;" t="&#x0059;"  note=" Y "   />
<s d="&#x005A;" t="&#x005A;"  note=" Z "   />
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="&#8364;" t="&#8364;"  note="euro" />
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&#x2039;" t="&#x2039;" note="French left single quotation mark" />
<s d="&#x203A;" t="&#x203A;" note="French right single quotation mark" />
<s d="&#x00AB;" t="&#x00AB;" note="French left double quotation mark" />
<s d="&#x00BB;" t="&#x00BB;" note="French right double quotation mark" />
<s d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s d="&#x0027;" t="&#x0027;" note="vertical single quote" />
<s d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/> 
</group>
</alphabet>
<alphabet name="Catal&#x00E0; / Catalan (combining accents) with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_catalanC_ES.txt</train>
<space d="&#x25a1;" t=" " b="9" note="box" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="Combining accents" b="191"  visible="on">
<s d="&#x25cc;&#x0300;"  t="&#x0300;" b="72" note="COMBINING GRAVE ACCENT &#x0060; "/>
<s d="&#x25cc;&#x0301;"  t="&#x0301;" b="82" note="COMBINING ACUTE ACCENT &#x00B4; "/>
<s d="&#x25cc;&#x0302;"  t="&#x0302;" b="72" note="COMBINING CIRCUMFLEX ACCENT  &#x005E; "/>
<s d="&#x25cc;&#x0303;"  t="&#x0303;" b="82" note="COMBINING TILDE &#x007E;  "/>
<s d="&#x25cc;&#x0304;"  t="&#x0304;" b="72" note="COMBINING MACRON  &#x00AF; "/>
<s d="&#x25cc;&#x0327;"  t="&#x0327;" b="82" note="COMBINING CEDILLA &#x00B8; "/>
<s d="&#x25cc;&#x0308;"  t="&#x0308;" b="72" note="COMBINING DIAERESIS or UMLAUT  &#x00A8;"/>
</group>
<group name="Lower case Latin letters"  visible="off">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters"  b="111">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="O" t="O" b="24"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="91"/>
<s d="3" t="3" b="92"/>
<s d="4" t="4" b="93"/>
<s d="5" t="5" b="94"/>
<s d="6" t="6" b="90"/>
<s d="7" t="7" b="91"/>
<s d="8" t="8" b="92"/>
<s d="9" t="9" b="93"/>
<s d="0" t="0" b="94"/>
</group>
<group name="Punctuation" b="112">
<s b="90" d="%" t="%"/>
<s b="91" d="*" t="*"/>
<s b="92" d="+" t="+"/>
<s b="93" d="=" t="="/>
<s b="94" d="/" t="/"/>
<s b="95" d="#" t="#"/>
<s d="&#8364;" t="&#8364;" b="96" note="euro" />
<s b="98" d="$" t="$"/>
<s b="99" d="|" t="|"/>
<s b="95" d="\" t="\"/>
<s b="96" d="~" t="~"/>
<s b="97" d="^" t="^"/>
<s b="98" d="_" t="_"/>
<s b="99" d="&amp;" t="&amp;"/> 
<s b="95" d="@" t="@"/>
<s b="105" d="[" t="["/>
<s b="106" d="]" t="]"/>
<s b="107" d="{" t="{"/>
<s b="108" d="}" t="}"/>
<s b="109" d="&lt;" t="&lt;"/>
<s b="105" d="&gt;" t="&gt;"/>
<s b="106" d="(" t="("/>
<s b="107" d=")" t=")"/>
<s b="107" d="&#x203A;" t="&#x203A;" note="French right single quotation mark" />
<s b="108" d="&#x2039;" t="&#x2039;" note="French left single quotation mark" />
<s b="109" d="&#x00BB;" t="&#x00BB;" note="French right double quotation mark" />
<s b="105" d="&#x00AB;" t="&#x00AB;" note="French left double quotation mark" />
<s b="106" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<!-- <s b="106" d="&#x0027;" t="&#x0027;" note="vertical single quote" /> -->
<s b="107" d="&#x25cc;&#x0313;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="9"    d="&#x25CA;" t="&#x9;" note="TAB (represented by a diamond)"/>
<s b="100"  d="-" t="-"/>
<s b="101"  d=":" t=":"/>
<s b="102"  d=";" t=";"/>
<s b="103"  d="?" t="?"/>
<s b="104"  d="!" t="!"/>
<s b="100"  d="," t=","/>
<s b="104" d="&#183;" t="."/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.finnish2.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="fi">
<alphabet name="Suomalainen / Finnish with limited punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_finnish_FI.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="lower case letters" b="0">
<s d="&#x0061;" t="&#x0061;" />
<s d="&#x0062;" t="&#x0062;" />
<s d="&#x0063;" t="&#x0063;" />
<s d="&#x0064;" t="&#x0064;" />
<s d="&#x0065;" t="&#x0065;" />
<s d="&#x0066;" t="&#x0066;" />
<s d="&#x0067;" t="&#x0067;" />
<s d="&#x0068;" t="&#x0068;" />
<s d="&#x0069;" t="&#x0069;" />
<s d="&#x006A;" t="&#x006A;" />
<s d="&#x006B;" t="&#x006B;" />
<s d="&#x006C;" t="&#x006C;" />
<s d="&#x006D;" t="&#x006D;" />
<s d="&#x006E;" t="&#x006E;" />
<s d="&#x006F;" t="&#x006F;" />
<s d="&#x0070;" t="&#x0070;" />
<s d="&#x0071;" t="&#x0071;" />
<s d="&#x0072;" t="&#x0072;" />
<s d="&#x0073;" t="&#x0073;" />
<s d="&#x0161;" t="&#x0161;" />
<s d="&#x0074;" t="&#x0074;" />
<s d="&#x0075;" t="&#x0075;" />
<s d="&#x0076;" t="&#x0076;" />
<s d="&#x0077;" t="&#x0077;" />
<s d="&#x0078;" t="&#x0078;" />
<s d="&#x0079;" t="&#x0079;" />
<s d="&#x00FC;" t="&#x00FC;" />
<s d="&#x007A;" t="&#x007A;" />
<s d="&#x017E;" t="&#x017E;" />
<s d="&#x00E5;" t="&#x00E5;" />
<s d="&#x00E4;" t="&#x00E4;" />
<s d="&#x00E6;" t="&#x00E6;" />
<s d="&#x00F6;" t="&#x00F6;" />
<s d="&#x00F8;" t="&#x00F8;" />
</group>
<group name="upper case letters" b="111">
<s d="&#x0041;" t="&#x0041;" />
<s d="&#x0042;" t="&#x0042;" />
<s d="&#x0043;" t="&#x0043;" />
<s d="&#x0044;" t="&#x0044;" />
<s d="&#x0045;" t="&#x0045;" />
<s d="&#x0046;" t="&#x0046;" />
<s d="&#x0047;" t="&#x0047;" />
<s d="&#x0048;" t="&#x0048;" />
<s d="&#x0049;" t="&#x0049;" />
<s d="&#x004A;" t="&#x004A;" />
<s d="&#x004B;" t="&#x004B;" />
<s d="&#x004C;" t="&#x004C;" />
<s d="&#x004D;" t="&#x004D;" />
<s d="&#x004E;" t="&#x004E;" />
<s d="&#x004F;" t="&#x004F;" />
<s d="&#x0050;" t="&#x0050;" />
<s d="&#x0051;" t="&#x0051;" />
<s d="&#x0052;" t="&#x0052;" />
<s d="&#x0053;" t="&#x0053;" />
<s d="&#x0160;" t="&#x0160;" />
<s d="&#x0054;" t="&#x0054;" />
<s d="&#x0055;" t="&#x0055;" />
<s d="&#x0056;" t="&#x0056;" />
<s d="&#x0057;" t="&#x0057;" />
<s d="&#x0058;" t="&#x0058;" />
<s d="&#x0059;" t="&#x0059;" />
<s d="&#x00DC;" t="&#x00DC;" />
<s d="&#x005A;" t="&#x005A;" />
<s d="&#x017D;" t="&#x017D;" />
<s d="&#x00C5;" t="&#x00C5;" />
<s d="&#x00C4;" t="&#x00C4;" />
<s d="&#x00C6;" t="&#x00C6;" />
<s d="&#x00D6;" t="&#x00D6;" />
<s d="&#x00D8;" t="&#x00D8;" />
</group>
<group name="Punctuation" b="112">
<s d="&apos;" t="&apos;"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="." t="."/>
</group>
</alphabet>
<!--<alphabet name="Suomalainen / Finnish lower case">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_finnishL_FI.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="lower case letters" b="0">
<s d="&#x0061;" t="&#x0061;" />
<s d="&#x0062;" t="&#x0062;" />
<s d="&#x0063;" t="&#x0063;" />
<s d="&#x0064;" t="&#x0064;" />
<s d="&#x0065;" t="&#x0065;" />
<s d="&#x0066;" t="&#x0066;" />
<s d="&#x0067;" t="&#x0067;" />
<s d="&#x0068;" t="&#x0068;" />
<s d="&#x0069;" t="&#x0069;" />
<s d="&#x006A;" t="&#x006A;" />
<s d="&#x006B;" t="&#x006B;" />
<s d="&#x006C;" t="&#x006C;" />
<s d="&#x006D;" t="&#x006D;" />
<s d="&#x006E;" t="&#x006E;" />
<s d="&#x006F;" t="&#x006F;" />
<s d="&#x0070;" t="&#x0070;" />
<s d="&#x0071;" t="&#x0071;" />
<s d="&#x0072;" t="&#x0072;" />
<s d="&#x0073;" t="&#x0073;" />
<s d="&#x0161;" t="&#x0161;" />
<s d="&#x0074;" t="&#x0074;" />
<s d="&#x0075;" t="&#x0075;" />
<s d="&#x0076;" t="&#x0076;" />
<s d="&#x0077;" t="&#x0077;" />
<s d="&#x0078;" t="&#x0078;" />
<s d="&#x0079;" t="&#x0079;" />
<s d="&#x00FC;" t="&#x00FC;" />
<s d="&#x007A;" t="&#x007A;" />
<s d="&#x017E;" t="&#x017E;" />
<s d="&#x00E5;" t="&#x00E5;" />
<s d="&#x00E4;" t="&#x00E4;" />
<s d="&#x00E6;" t="&#x00E6;" />
<s d="&#x00F6;" t="&#x00F6;" />
<s d="&#x00F8;" t="&#x00F8;" />
</group>
<group name="Punctuation" b="112">
<s d="." t="."/>
</group>
</alphabet>-->
</alphabets>

=== GNOME/dasher/Data/alphabets/alphabet.albanian.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets langcode="sq">
<alphabet name="Shqip / Albanian with punctuation and numerals">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Default</palette>
<train>training_albanian_SQ.txt</train>
<space d="&#x25a1;" t=" " b="9" note="box" />
<control d="Control" t="" b="8"/>
<paragraph d="&#182;" b="9"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a"/>
<s d="b" t="b"/>
<s d="c" t="c"/>
<s d="&#x00E7;" t="&#x00E7;"/>
<s d="d" t="d"/>
<s d="e" t="e"/>
<s d="&#x00EB;" t="&#x00EB;"/>
<s d="f" t="f"/>
<s d="g" t="g"/>
<s d="h" t="h"/>
<s d="i" t="i"/>
<s d="j" t="j"/>
<s d="k" t="k"/>
<s d="l" t="l"/>
<s d="m" t="m"/>
<s d="n" t="n"/>
<s d="o" t="o"/>
<s d="p" t="p"/>
<s d="q" t="q"/>
<s d="r" t="r"/>
<s d="s" t="s"/>
<s d="t" t="t"/>
<s d="u" t="u"/>
<s d="v" t="v"/>
<s d="x" t="x"/>
<s d="y" t="y"/>
<s d="z" t="z"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A"/>
<s d="B" t="B"/>
<s d="C" t="C"/>
<s d="&#x00C7;" t="&#x00C7;"/>
<s d="D" t="D"/>
<s d="E" t="E"/>
<s d="&#x00CB;" t="&#x00CB;"/>
<s d="F" t="F"/>
<s d="G" t="G"/>
<s d="H" t="H"/>
<s d="I" t="I"/>
<s d="J" t="J"/>
<s d="K" t="K"/>
<s d="L" t="L"/>
<s d="M" t="M"/>
<s d="N" t="N"/>
<s d="O" t="O"/>
<s d="P" t="P"/>
<s d="Q" t="Q"/>
<s d="R" t="R"/>
<s d="S" t="S"/>
<s d="T" t="T"/>
<s d="U" t="U"/>
<s d="V" t="V"/>
<s d="X" t="X"/>
<s d="Y" t="Y"/>
<s d="Z" t="Z"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1"/>
<s d="2" t="2"/>
<s d="3" t="3"/>
<s d="4" t="4"/>
<s d="5" t="5"/>
<s d="6" t="6"/>
<s d="7" t="7"/>
<s d="8" t="8"/>
<s d="9" t="9"/>
<s d="0" t="0"/>
</group>
<group name="Punctuation" b="112">
<s d="%" t="%"/>
<s d="*" t="*"/>
<s d="+" t="+"/>
<s d="=" t="="/>
<s d="/" t="/"/>
<s d="#" t="#"/>
<s d="$" t="$"/>
<s d="|" t="|"/>
<s d="\" t="\"/>
<s d="~" t="~"/>
<s d="^" t="^"/>
<s d="_" t="_"/>
<s d="&amp;" t="&amp;"/>
<s d="@" t="@"/>
<s d="[" t="["/>
<s d="]" t="]"/>
<s d="{" t="{"/>
<s d="}" t="}"/>
<s d="&lt;" t="&lt;"/>
<s d="&gt;" t="&gt;"/>
<s d="(" t="("/>
<s d=")" t=")"/>
<s d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s d="&#x201A;" t="&#x201A;" note="German left single quotation mark; Albanian right" />
<s d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s d="&#x201E;" t="&#x201E;" note="German left double quotation mark; Albanian right" />
<s d="&#x2039;" t="&#x2039;" note="French left single quotation mark" />
<s d="&#x203A;" t="&#x203A;" note="French right single quotation mark" />
<s d="&#x00AB;" t="&#x00AB;" note="French left double quotation mark" />
<s d="&#x00BB;" t="&#x00BB;" note="French right double quotation mark" />
<s d="-" t="-"/>
<s d=":" t=":"/>
<s d=";" t=";"/>
<s d="?" t="?"/>
<s d="!" t="!"/>
<s d="," t=","/>
<s d="&#183;" t="."/>
</group>
</alphabet>
</alphabets>
