=== GNOME/dasher/java/src/main/java/dasher/applet/system.rc/alphabet.dtd
<!-- alphabets contains groups of valid symbols for use in Dasher,
along with some useful information. It does nothing to tell Dasher,
how those symbols may be used. -->

<!ELEMENT alphabets (alphabet*)>

<!ELEMENT alphabet (orientation, encoding, train, paragraph, space, control, group*)>
<!ATTLIST alphabet name CDATA #REQUIRED>

<!-- Left-Right, Right-Left, Top-Bottom or Bottom-Top?
Which way up should Dasher do its rendering by default? -->
<!ELEMENT orientation EMPTY>
<!ATTLIST orientation type (LR|RL|TB|BT) #REQUIRED>

<!-- The encoding field just helps Dasher decide on some Localisation
issues. In theory it could see which characters are there and pick
a suitable file encoding and font. Sometimes this is difficult.
It does not dictate the file format. For example, traditionally Unix
and Windows use different encodings for some languages. A platform
should do what what it thinks best given the vague group Dasher
has put the alphabet into. If this doesn't work out, the user
can over-ride the alphabet anyway. -->
<!ELEMENT encoding EMPTY>
<!ATTLIST encoding type CDATA #REQUIRED>

<!-- Default training file for this alphabet -->
<!ELEMENT train (#PCDATA)>

<!-- Traditionally the paragraph character is rendered differently to all
others. Can set d (display) to "" to disable. -->
<!ELEMENT paragraph EMPTY>
<!ATTLIST paragraph d CDATA #REQUIRED>
<!ATTLIST paragraph f CDATA #IMPLIED>
<!ATTLIST paragraph b CDATA #IMPLIED>

<!-- Traditionally the space character is rendered differently to all
others. Can set both d (display) and t (text) to "" to disable. -->
<!ELEMENT space EMPTY>
<!ATTLIST space d CDATA #REQUIRED>
<!ATTLIST space t CDATA #REQUIRED>
<!ATTLIST space f CDATA #IMPLIED>
<!ATTLIST space b CDATA #IMPLIED>

<!-- The control character is special, and not part of the main alphabet. -->

<!ELEMENT control EMPTY>
<!ATTLIST control d CDATA #REQUIRED>
<!ATTLIST control t CDATA #REQUIRED>
<!ATTLIST control f CDATA #IMPLIED>
<!ATTLIST control b CDATA #IMPLIED>

<!-- Logical groups of symbols, eg name="Lower case letters" -->
<!ELEMENT group (s*)>
<!ATTLIST group name CDATA #REQUIRED>
<!ATTLIST group b CDATA #IMPLIED>

<!-- Symbols Dasher can use. It shows text d in the nodes and sends
text t to the edit box -->
<!ELEMENT s EMPTY>
<!ATTLIST s d CDATA #REQUIRED>
<!ATTLIST s t CDATA #REQUIRED>
<!ATTLIST s f CDATA #IMPLIED>
<!ATTLIST s b CDATA #IMPLIED>

=== GNOME/dasher/java/src/main/java/dasher/applet/system.rc/alphabet.englishC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets>
<alphabet name="English with accents, numerals, punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian (New)</palette>
<train>training_english_GB.txt</train>
<space d="&#x25a1;" t=" "  b="9"/>
<control d="Control" t=""  b="8"/>
<paragraph d="&#182;" b="9"/>
<group name="Combining accents" b="47" visible="on">
<s d="&#x25cc;&#x0300;"  t="&#x0300;" b="40" note="&#x0060; COMBINING GRAVE ACCENT  "/>
<s d="&#x25cc;&#x0301;"  t="&#x0301;" b="41" note="&#x00B4; COMBINING ACUTE ACCENT  "/>
<s d="&#x25cc;&#x0302;"  t="&#x0302;" b="40" note="&#x005E; COMBINING CIRCUMFLEX ACCENT  "/>
<s d="&#x25cc;&#x0303;"  t="&#x0303;" b="41" note="&#x007E; COMBINING TILDE  "/>
<s d="&#x25cc;&#x0304;"  t="&#x0304;" b="40" note="&#x00AF; COMBINING MACRON  "/>
<s d="&#x25cc;&#x0306;"  t="&#x0306;" b="41" note="&#x02D8; COMBINING BREVE"/>
<s d="&#x25cc;&#x0307;"  t="&#x0307;" b="40" note="&#x02D9; COMBINING DOT ABOVE"/>
<s d="&#x25cc;&#x0308;"  t="&#x0308;" b="41" note="&#x00A8; COMBINING DIAERESIS or UMLAUT "/>
<s d="&#x25cc;&#x030A;"  t="&#x030A;" b="40" note="&#x02DA; COMBINING RING ABOVE"/>
<s d="&#x25cc;&#x030B;"  t="&#x030B;" b="41" note="&#x02DD; COMBINING DOUBLE ACUTE ACCENT"/>
<s d="&#x25cc;&#x030C;"  t="&#x030C;" b="40" note="&#x02C7; COMBINING CARON"/>
<s d="&#x25cc;&#x0326;"  t="&#x0326;" b="41" note="       COMBINING COMMA BELOW"/>
<s d="&#x25cc;&#x0327;"  t="&#x0327;" b="40" note="&#x00B8; COMBINING CEDILLA  "/>
<s d="&#x25cc;&#x0328;"  t="&#x0328;" b="41" note="&#x02DB; COMBINING OGONEK"/>
</group>
<group name="Lower case Latin letters" b="0" visible="off">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="46">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="O" t="O" b="24"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Numbers" b="48">
<s d="1" t="1" b="42"/>
<s d="2" t="2" b="41"/>
<s d="3" t="3" b="42"/>
<s d="4" t="4" b="41"/>
<s d="5" t="5" b="42"/>
<s d="6" t="6" b="41"/>
<s d="7" t="7" b="42"/>
<s d="8" t="8" b="41"/>
<s d="9" t="9" b="42"/>
<s d="0" t="0" b="41"/>
</group>
<group name="Punctuation" b="49">
<s b="40" d="[" t="["/>
<s b="41" d="]" t="]"/>
<s b="40" d="{" t="{"/>
<s b="41" d="}" t="}"/>
<s b="40" d="&lt;" t="&lt;"/>
<s b="41" d="&gt;" t="&gt;"/>
<s b="40" d="(" t="("/>
<s b="41" d=")" t=")"/>
<s b="40" d="&amp;" t="&amp;"/> 
<s b="42" d="$" t="$"/>
<s b="41" d="%" t="%"/>
<s b="42" d="=" t="="/>
<s b="41" d="+" t="+"/>
<s b="42" d="-" t="-"/>
<s b="41" d="*" t="*"/>
<s b="42" d="/" t="/"/>
<s b="40" d="\" t="\"/>
<s b="41" d="#" t="#"/>
<s b="40" d="|" t="|"/>
<s b="41" d="~" t="~"/>
<s b="40" d="^" t="^"/>
<s b="41" d="@" t="@"/>
<s b="40" d="_" t="_"/>
<s b="42" d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s b="41" d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s b="42" d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s b="41" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s b="42" d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="41" d="`" t="`" note="left quote from keyboard" />
<s b="42" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<s b="40"  d="&#x25CA;" t="&#x9;" note="TAB (represented by a diamond)"/>
<s b="41" d=":" t=":"/>
<s b="40" d=";" t=";"/>
<s b="41" d="?" t="?"/>
<s b="40" d="!" t="!"/>
<s b="41" d="," t=","/>
<s d="&#183;" t="." b="40"/>
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/java/src/main/java/dasher/applet/system.rc/alphabet.english.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets>
<alphabet name="English with limited punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_english_GB.txt</train>
<paragraph d="&#182;" b="9"/>
<space d="&#x25a1;" t=" " b="9" note="box" />
<control d="Control" t="" b="8"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="O" t="O" b="24"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Punctuation" b="112">
<s d="&amp;" t="&amp;" b="99"/>
<s d="&quot;" t="&quot;" b="109"/>
<s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<!-- <s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/> -->
<!-- <s b="105" d="&#x2323;&#x0313;" t="&apos;" note=" apostrophe above a smile arc"/> -->
<!-- <s b="105" d="&#x2319;&#x0313;" t="&apos;" note=" apostrophe"/> -->
<s d="?" t="?" b="103"/>
<s d="!" t="!" b="104"/>
<!-- <s d="&#x2312;&#x0326;" t="," b="100" note="overarced comma"/> -->
<s d="," t="," b="100" note="&#x236A; overlined comma"/>
<s d="&#183;" t="." b="104"/>
</group>
</alphabet>
<alphabet name="English with numerals and limited punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_english_GB.txt</train>
<paragraph d="&#182;" b="9"/>
<space d="&#x25a1;" t=" " b="9" note="box" />
<control d="Control" t="" b="8"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="O" t="O" b="24"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="91"/>
<s d="3" t="3" b="92"/>
<s d="4" t="4" b="93"/>
<s d="5" t="5" b="94"/>
<s d="6" t="6" b="90"/>
<s d="7" t="7" b="91"/>
<s d="8" t="8" b="92"/>
<s d="9" t="9" b="93"/>
<s d="0" t="0" b="94"/>
</group>
<group name="Punctuation" b="112">
<s d="&amp;" t="&amp;" b="99"/>
<s d="&quot;" t="&quot;" b="109"/>
<s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<s d="?" t="?" b="103"/>
<s d="!" t="!" b="104"/>
<s d="," t="," b="100"/>
<s d="&#183;" t="." b="104"/>
</group>
</alphabet>
<alphabet name="English with numerals and lots of punctuation">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_english_GB.txt</train>
<space d="&#x25a1;" t=" "  b="9"/>
<control d="Control" t=""/>
<paragraph d="&#182;" b="9"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Upper case Latin letters" b="111">
<s d="A" t="A" b="10"/>
<s d="B" t="B" b="11"/>
<s d="C" t="C" b="12"/>
<s d="D" t="D" b="13"/>
<s d="E" t="E" b="14"/>
<s d="F" t="F" b="15"/>
<s d="G" t="G" b="16"/>
<s d="H" t="H" b="17"/>
<s d="I" t="I" b="18"/>
<s d="J" t="J" b="19"/>
<s d="K" t="K" b="20"/>
<s d="L" t="L" b="21"/>
<s d="M" t="M" b="22"/>
<s d="N" t="N" b="23"/>
<s d="O" t="O" b="24"/>
<s d="P" t="P" b="25"/>
<s d="Q" t="Q" b="26"/>
<s d="R" t="R" b="27"/>
<s d="S" t="S" b="28"/>
<s d="T" t="T" b="29"/>
<s d="U" t="U" b="30"/>
<s d="V" t="V" b="31"/>
<s d="W" t="W" b="32"/>
<s d="X" t="X" b="33"/>
<s d="Y" t="Y" b="34"/>
<s d="Z" t="Z" b="35"/>
</group>
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="91"/>
<s d="3" t="3" b="92"/>
<s d="4" t="4" b="93"/>
<s d="5" t="5" b="94"/>
<s d="6" t="6" b="90"/>
<s d="7" t="7" b="91"/>
<s d="8" t="8" b="92"/>
<s d="9" t="9" b="93"/>
<s d="0" t="0" b="94"/>
</group>
<group name="Punctuation" b="112">
<s b="90" d="%" t="%"/>
<s b="91" d="*" t="*"/>
<s b="92" d="+" t="+"/>
<s b="93" d="=" t="="/>
<s b="94" d="/" t="/"/>
<s b="95" d="#" t="#"/>
<s d="&#8364;" t="&#8364;" b="96" note="euro" />
<s b="97"  d="&#163;" t="&#163;" note="Pound" />
<s b="98" d="$" t="$"/>
<s b="99" d="|" t="|"/>
<s b="95" d="\" t="\"/>
<s b="96" d="~" t="~"/>
<s b="97" d="^" t="^"/>
<s b="98" d="_" t="_"/>
<s b="99" d="&amp;" t="&amp;"/> 
<s b="95" d="@" t="@"/>
<s b="105" d="[" t="["/>
<s b="106" d="]" t="]"/>
<s b="107" d="{" t="{"/>
<s b="108" d="}" t="}"/>
<s b="109" d="&lt;" t="&lt;"/>
<s b="105" d="&gt;" t="&gt;"/>
<s b="106" d="(" t="("/>
<s b="107" d=")" t=")"/>
<s b="108" d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s b="109" d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s b="106" d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s b="107" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s b="108" d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="109" d="`" t="`" note="left quote from keyboard" />
<s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<s b="9"  d="&#x25CA;" t="&#x9;" note="TAB (represented by a diamond)"/>
<s b="100" d="-" t="-"/>
<s b="101" d=":" t=":"/>
<s b="102" d=";" t=";"/>
<s b="103" d="?" t="?"/>
<s b="104" d="!" t="!"/>
<s b="100" d="," t=","/>
<s d="&#183;" t="." b="104"/>
</group>
</alphabet>
<alphabet name="English, lower case">
<orientation type="LR"/>
<encoding type="Western"/>
<palette>European/Asian</palette>
<train>training_englishLC_GB.txt</train>
<space d="&#x25a1;" t=" " b="9" note="box" />
<control d="Control" t="" b="8"/>
<group name="Lower case Latin letters" b="0">
<s d="a" t="a" b="10"/>
<s d="b" t="b" b="11"/>
<s d="c" t="c" b="12"/>
<s d="d" t="d" b="13"/>
<s d="e" t="e" b="14"/>
<s d="f" t="f" b="15"/>
<s d="g" t="g" b="16"/>
<s d="h" t="h" b="17"/>
<s d="i" t="i" b="18"/>
<s d="j" t="j" b="19"/>
<s d="k" t="k" b="20"/>
<s d="l" t="l" b="21"/>
<s d="m" t="m" b="22"/>
<s d="n" t="n" b="23"/>
<s d="o" t="o" b="24"/>
<s d="p" t="p" b="25"/>
<s d="q" t="q" b="26"/>
<s d="r" t="r" b="27"/>
<s d="s" t="s" b="28"/>
<s d="t" t="t" b="29"/>
<s d="u" t="u" b="30"/>
<s d="v" t="v" b="31"/>
<s d="w" t="w" b="32"/>
<s d="x" t="x" b="33"/>
<s d="y" t="y" b="34"/>
<s d="z" t="z" b="35"/>
</group>
<group name="Punctuation" b="112">
<s b="105" d="&#x25cc;&#x0313;"  t="&apos;" />
<s b="103" d="?" t="?" />
<s b="104" d="!" t="!" />
<s b="100" d="," t="," />
<s b="104" d="&#183;" t="." />
</group>
</alphabet>
</alphabets>

=== GNOME/dasher/java/src/main/java/dasher/applet/system.rc/alphabet.Thai.xml
<?xml version="1.0"?>
<!DOCTYPE alphabets SYSTEM "alphabet.dtd">
<?xml-stylesheet type="text/xsl" href="alphabet.xsl"?>
<alphabets>
<alphabet name="Thai / &#3616;&#3634;&#3625;&#3634;&#3652;&#3607;&#3618; with punctuation and numerals">
<!-- the Thai alphabet does not distinguish minuscule and majuscule letters. It is usually written with no space between words; most Thai words have only one syllable. The end of sentences is marked by a space  -->
<orientation type="LR"/>
<encoding type="Western"/>
<palette>Thai</palette>
<train>training_Thai_TH.txt</train>
<space d="&#x25a1;" t=" " b="9" />
<paragraph d="&#182;" b="9"/>
<control d="Control" t="" b="8"/>
<group name="Vowels"  b="111"  visible="on">
<s d="&#x25cc;&#x0E4D;" t="&#x0E4D;" b="82" note="NIKHAHIT    UNUSED?" />
<s d="&#x25cc;&#x0E30;" t="&#x0E30;" b="72" note="SARA A" />
<s d="&#x25cc;&#x0E31;" t="&#x0E31;" b="82" note="tone MAI HAN-AKAT" />
<s d="&#x25cc;&#x0E32;" t="&#x0E32;" b="72" note=" SARA AA"/>
<s d="&#x25cc;&#x0E45;" t="&#x0E45;" b="82" note=" LAKKHANGYAO  UNUSED?" />
<s d="&#x25cc;&#x0E33;" t="&#x0E33;" b="72" note="SARA AM"/>
<s d="&#x25cc;&#x0E34;" t="&#x0E34;" b="82" />
<s d="&#x25cc;&#x0E35;" t="&#x0E35;" b="72" />
<s d="&#x25cc;&#x0E36;" t="&#x0E36;" b="82" />
<s d="&#x25cc;&#x0E37;" t="&#x0E37;" b="72" />
<s d="&#x25cc;&#x0E38;" t="&#x0E38;" b="82" />
<s d="&#x25cc;&#x0E39;" t="&#x0E39;" b="72" />
<s d="&#x0E40;&#x25cc;" t="&#x0E40;" b="82" note="0E40	 SARA E"/>	    
<s d="&#x0E41;&#x25cc;" t="&#x0E41;" b="72" note="0E41	 SARA AE"/>	    
<s d="&#x0E42;&#x25cc;" t="&#x0E42;" b="82" note="0E42	 SARA O"/>	    
<s d="&#x0E43;&#x25cc;" t="&#x0E43;" b="72" note="0E43	 SARA AI MAIMUAN"/> 
<s d="&#x0E44;&#x25cc;" t="&#x0E44;" b="82" note="0E44	 SARA AI MAIMALAI"/>
<s d="&#x25cc;&#x0E3A;" t="&#x0E3A;" b="72" note="0E3A PHINTHU -     UNUSED?"/>
<s d="&#x25cc;&#x0E4C;" t="&#x0E4C;" b="82" note="0E4C	 THANTHAKHAT - CHECK"/>
<s d="&#x25cc;&#x0E4E;" t="&#x0E4E;" b="82" note="0E4E	 YAMAKKAN -     UNUSED?"/>
</group>
<group name="Tones"  b="193"  visible="on">
<s d="&#x25cc;&#x0E47;" t="&#x0E47;" b="83" note="0E47 tone MAITAIKHU"/>
<s d="&#x25cc;&#x0E48;" t="&#x0E48;" b="73" note="0E48 tone MAI EK"/>
<s d="&#x25cc;&#x0E49;" t="&#x0E49;" b="83" note="0E49 tone MAI THO"/>
<s d="&#x25cc;&#x0E4A;" t="&#x0E4A;" b="73" note="0E4A tone MAI TRI"/>
<s d="&#x25cc;&#x0E4B;" t="&#x0E4B;" b="83" note="0E4B tone MAI CHATTAWA"/>
</group>
<group name="Thai letters" b="0" visible="off">
<s d="&#x0E01;" t="&#x0E01;" b="10" note="middle-tone 0E01 KO KAI"/>
<s d="&#x0E02;" t="&#x0E02;" b="11" note="high-tone 0E02 KHO KHAI"/>
<s d="&#x0E03;" t="&#x0E03;" b="12" note="high-tone 0E03 KHO KHUAT  UNUSED?"/>
<s d="&#x0E04;" t="&#x0E04;" b="13" note="low-tone 0E04 KHO KHWAI "/>
<s d="&#x0E05;" t="&#x0E05;" b="14" note="low-tone 0E05 KHO KHON    UNUSED?"/>
<s d="&#x0E06;" t="&#x0E06;" b="15" note="low-tone 0E06 KHO RAKHANG"/>
<s d="&#x0E07;" t="&#x0E07;" b="16" note="low-tone 0E07 NGO NGU"/>
<s d="&#x0E08;" t="&#x0E08;" b="17" note="middle-tone 0E08 CHO CHAN"/>
<s d="&#x0E09;" t="&#x0E09;" b="18" note="high-tone 0E09 CHO CHING"/>
<s d="&#x0E0A;" t="&#x0E0A;" b="19" note="low-tone 0E0A CHO CHANG"/>
<s d="&#x0E0B;" t="&#x0E0B;" b="20" note="low-tone 0E0B SO SO"/>
<s d="&#x0E0C;" t="&#x0E0C;" b="21" note="low-tone 0E0C CHO CHOE"/>
<s d="&#x0E0D;" t="&#x0E0D;" b="22" note="low-tone 0E0D YO YING"/>
<s d="&#x0E0E;" t="&#x0E0E;" b="23" note="middle-tone 0E0E DO CHADA"/>
<s d="&#x0E0F;" t="&#x0E0F;" b="24" note="middle-tone 0E0F TO PATAK"/>
<s d="&#x0E10;" t="&#x0E10;" b="25" note="high-tone 0E10 THO THAN"/>
<s d="&#x0E11;" t="&#x0E11;" b="26" note="low-tone 0E11 THO NANGMONTHO"/>
<s d="&#x0E12;" t="&#x0E12;" b="27" note="low-tone 0E12 THO PHUTHAO"/>
<s d="&#x0E13;" t="&#x0E13;" b="28" note="low-tone 0E13 NO NEN"/>
<s d="&#x0E14;" t="&#x0E14;" b="29" note="middle-tone 0E14 DO DEK"/>
<s d="&#x0E15;" t="&#x0E15;" b="30" note="middle-tone 0E15 TO TAO"/>
<s d="&#x0E16;" t="&#x0E16;" b="31" note="high-tone 0E16 THO THUNG"/>
<s d="&#x0E17;" t="&#x0E17;" b="32" note="low-tone 0E17 THO THAHAN"/>
<s d="&#x0E18;" t="&#x0E18;" b="33" note="low-tone 0E18 THO THONG"/>
<s d="&#x0E19;" t="&#x0E19;" b="34" note="low-tone 0E19 NO NU"/>
<s d="&#x0E1A;" t="&#x0E1A;" b="35" note="middle-tone 0E1A BO BAIMAI"/>
<s d="&#x0E1B;" t="&#x0E1B;" b="36" note="middle-tone 0E1B PO PLA"/>
<s d="&#x0E1C;" t="&#x0E1C;" b="37" note="high-tone 0E1C PHO PHUNG"/>
<s d="&#x0E1D;" t="&#x0E1D;" b="38" note="high-tone 0E1D FO FA"/>
<s d="&#x0E1E;" t="&#x0E1E;" b="39" note="low-tone 0E1E PHO PHAN"/>
<s d="&#x0E1F;" t="&#x0E1F;" b="40" note="low-tone 0E1F FO FAN"/>
<s d="&#x0E20;" t="&#x0E20;" b="41" note="low-tone 0E20 PHO SAMPHAO"/>
<s d="&#x0E21;" t="&#x0E21;" b="42" note="low-tone 0E21 MO MA"/>
<s d="&#x0E22;" t="&#x0E22;" b="43" note="low-tone 0E22 YO YAK"/>
<s d="&#x0E23;" t="&#x0E23;" b="44" note="low-tone 0E23 RO RUA"/>
<s d="&#x0E24;" t="&#x0E24;" b="45" note="0E24 RU      WHAT TONE GROUP?"/>
<s d="&#x0E25;" t="&#x0E25;" b="46" note="low-tone 0E25 LO LING"/>
<s d="&#x0E26;" t="&#x0E26;" b="47" note="0E26 LU    UNUSED?"/>
<s d="&#x0E27;" t="&#x0E27;" b="48" note="low-tone 0E27 WO WAEN"/>
<s d="&#x0E28;" t="&#x0E28;" b="49" note="high-tone 0E28 SO SALA"/>
<s d="&#x0E29;" t="&#x0E29;" b="50" note="high-tone 0E29 SO RUSI"/>
<s d="&#x0E2A;" t="&#x0E2A;" b="51" note="high-tone 0E2A SO SUA"/>
<s d="&#x0E2B;" t="&#x0E2B;" b="52" note="high-tone 0E2B HO HIP"/>
<s d="&#x0E2C;" t="&#x0E2C;" b="53" note="low-tone 0E2C LO CHULA"/>
<s d="&#x0E2D;" t="&#x0E2D;" b="54" note="middle-tone 0E2D O ANG (null consonant)"/>
<s d="&#x0E2E;" t="&#x0E2E;" b="55" note="low-tone 0E2E HO NOKHUK"/>                 
</group>		    
<group name="Numbers" b="113">
<s d="1" t="1" b="90"/>
<s d="2" t="2" b="91"/>
<s d="3" t="3" b="92"/>
<s d="4" t="4" b="93"/>
<s d="5" t="5" b="94"/>
<s d="6" t="6" b="90"/>
<s d="7" t="7" b="91"/>
<s d="8" t="8" b="92"/>
<s d="9" t="9" b="93"/>
<s d="0" t="0" b="94"/>
</group>
<group name="Thai digits" b="113">
<s d="&#x0E51;" t="&#x0E51;" b="90" note="0E51	THAI DIGIT ONE"/>
<s d="&#x0E52;" t="&#x0E52;" b="91" note="0E52	THAI DIGIT TWO"/>
<s d="&#x0E53;" t="&#x0E53;" b="92" note="0E53	THAI DIGIT THREE"/>
<s d="&#x0E54;" t="&#x0E54;" b="93" note="0E54	THAI DIGIT FOUR"/>
<s d="&#x0E55;" t="&#x0E55;" b="94" note="0E55	THAI DIGIT FIVE"/>
<s d="&#x0E56;" t="&#x0E56;" b="90" note="0E56	THAI DIGIT SIX"/>
<s d="&#x0E57;" t="&#x0E57;" b="91" note="0E57	THAI DIGIT SEVEN"/>
<s d="&#x0E58;" t="&#x0E58;" b="92" note="0E58	THAI DIGIT EIGHT"/>
<s d="&#x0E59;" t="&#x0E59;" b="93" note="0E59	THAI DIGIT NINE"/>
<s d="&#x0E50;" t="&#x0E50;" b="94" note="0E50	THAI DIGIT ZERO"/>
</group>
<group name="Punctuation" b="112">
<s d="&#x0E4F;" t="&#x0E4F;" b="90" note="0E4F	 FONGMAN -    UNUSED?"/>
<s d="&#x0E5A;" t="&#x0E5A;" b="91" note="0E5A	THAI CHARACTER ANGKHANKHU -    UNUSED?"/>
<s d="&#x0E5B;" t="&#x0E5B;" b="92" note="0E5B	THAI CHARACTER KHOMUT  -    UNUSED?"/>
<s d="&#x0E2F;" t="&#x0E2F;" b="93" note="0E2F PAIYANNOI - means preceding word is abbreviated  CHECK"/>
<s d="&#x0E46;" t="&#x0E46;" b="94" note="THAI CHARACTER MAIYAMOK - means preceding word or phrase is repeated - CHECK" />
<s b="90" d="%" t="%"/>	   
<s b="91" d="*" t="*"/>	   
<s b="92" d="+" t="+"/>	   
<s b="93" d="=" t="="/>	   
<s b="94" d="/" t="/"/>	   
<s b="95" d="#" t="#"/>
<s d="&#x0E3F;" t="&#x0E3F;"  b="90"  note="0E3F	THAI CURRENCY SYMBOL BAHT"/>
<s b="98" d="$" t="$"/>
<s b="99" d="|" t="|"/>
<s b="95" d="\" t="\"/>
<s b="96" d="~" t="~"/>
<s b="97" d="^" t="^"/>
<s b="98" d="_" t="_"/>
<s b="99" d="&amp;" t="&amp;"/> 
<s b="95" d="@" t="@"/>
<s b="105" d="[" t="["/>
<s b="106" d="]" t="]"/>
<s b="107" d="{" t="{"/>
<s b="108" d="}" t="}"/>
<s b="109" d="&lt;" t="&lt;"/>
<s b="105" d="&gt;" t="&gt;"/>
<s b="106" d="(" t="("/>
<s b="107" d=")" t=")"/>
<s b="108" d="&#x201C;" t="&#x201C;" note="left double quotation mark" />
<s b="109" d="&#x0022;" t="&#x0022;" note="deprecated vertical double quotation mark" />
<s b="106" d="&#x201D;" t="&#x201D;" note="right double quotation mark" />
<s b="107" d="&#x2018;" t="&#x2018;" note="left single quotation mark" />
<s b="108" d="&#x2019;" t="&#x2019;" note="right single quotation mark and apostrophe" />
<s b="109" d="`" t="`" note="left quote from keyboard" />
<s b="105" d="&#x25cc;&#x0313;" t="&apos;" note=" apostrophe"/>
<s b="9"  d="&#x25CA;" t="&#x9;" note="TAB (represented by a diamond)"/>
<s b="100" d="-" t="-"/>
<s b="101" d=":" t=":"/>
<s b="102" d=";" t=";"/>
<s b="103" d="?" t="?"/>
<s b="104" d="!" t="!"/>
<s b="100" d="," t=","/>
<s d="&#183;" t="." b="104"/>
</group>
</alphabet>
</alphabets>
